//go:generate go install
package main

import (
	"go/ast"
	"fmt"
	"os"
	"go/token"
	"go/parser"
	"strings"
	"path/filepath"
	"text/template"
	"strconv"
	"sort"
)

var sNIL = struct {}{}

func getSelectorExpr(expr *ast.StarExpr) (m, sel string) {
	switch v := expr.X.(type) {
	case *ast.Ident:
		return "", v.Name
	case *ast.SelectorExpr:
		return v.X.(*ast.Ident).Name, v.Sel.Name
	default:
		return "", ""
	}
}

func getTypeName(expr *ast.StarExpr) (t string) {
	switch v := expr.X.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", v.X.(*ast.Ident).Name, v.Sel.Name)
	default:
		return ""
	}
}

func getPkgName(path string) string {
	goPath := os.Getenv("GOPATH")
	goRoot := os.Getenv("GOROOT")
	pkgPath := filepath.Join(goPath, "src", path)
	dPkgPath := filepath.Join(goRoot, "src", path)
	searchPaths := []string{pkgPath, dPkgPath}
	for _, p := range searchPaths {
		if _, e := os.Stat(p); !os.IsNotExist(e) {
			fs := token.NewFileSet()
			pkgs, err := parser.ParseDir(fs, pkgPath, nil, parser.PackageClauseOnly)
			if err != nil {
				//log.Println("p", err.Error())
			} else {
				for name := range pkgs {
					if strings.HasSuffix(name, "_test") == false {
						return name
					}
				}
			}
		}
	}
	return ""
}

func getImportName(path string) string {
	pkg := getPkgName(path)
	if pkg != "" {
		return pkg
	}
	paths := strings.Split(path, "/")
	return paths[len(paths)-1]
}

type Imp struct {
	PkgName string
	Alias string
	Path string
}

type HandleFunc struct {
	Proto    uint16
	FuncName string
	ReqType  string
	RespType string
}

type ProtoHandleGen struct {
	handlers []HandleFunc
	imps map[string]Imp
	pkgs map[string]struct{}
}

func (v *ProtoHandleGen)Visit(n ast.Node) ast.Visitor {
	switch node := n.(type) {
	case *ast.FuncDecl:
		Func := node
		if Func.Doc == nil {
			break
		}
		//fmt.Printf("Doc Text:\n%s", Func.Doc.Text())
		h := HandleFunc{}
		h.FuncName = Func.Name.Name
		for _, c := range Func.Doc.List {
			//fmt.Printf("%#v\n", c.Text)
			comment := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if strings.HasPrefix(comment, "proto:") {
				no, _ := strconv.Atoi(strings.TrimSpace(comment[6:]))
				h.Proto = uint16(no)
				break
			}
		}
		if h.Proto == 0 {
			break
		}
		if Func.Type.Params.NumFields() == 3 {
			ctxType, ok := Func.Type.Params.List[0].Type.(*ast.StarExpr)
			if ok {
				ctxStr := getTypeName(ctxType)
				if ctxStr != "menet.TcpSession" {
					fmt.Println("type error", ctxType)
					break
				}
			}
			reqType, ok1 := Func.Type.Params.List[1].Type.(*ast.StarExpr)
			respType, ok2 := Func.Type.Params.List[2].Type.(*ast.StarExpr)
			if ok1 && ok2 {
				m, n := getSelectorExpr(reqType)
				if m == "" && n == "" {
					break
				}
				h.ReqType = fmt.Sprintf("%s.%s", m, n)
				if Func.Type.Params.List[1].Names[0].Name == "_" {
					h.ReqType = "_"
				}
				v.pkgs[m] = sNIL
				m, n = getSelectorExpr(respType)
				if m == "" && n == "" {
					break
				}
				h.RespType = fmt.Sprintf("%s.%s", m, n)
				v.pkgs[m] = sNIL
			} else {
				break
			}
		} else {
			break
		}
		v.handlers = append(v.handlers, h)
	case *ast.ImportSpec:
		Import := node
		imp := Imp{}
		path := Import.Path.Value[1 : len(Import.Path.Value)-1]
		pkgName := getImportName(path)
		imp.PkgName = pkgName
		imp.Path = path
		if Import.Name != nil {
			imp.Alias = Import.Name.Name
		}
		v.imps[pkgName] = imp
	}
	return v
}

func (v *ProtoHandleGen)Gen() {
	goPackage := os.Getenv("GOPACKAGE")
	cwd, err := os.Getwd()
	var genFilePath string
	if cwd != "" {
		genFilePath = filepath.Join(cwd, "proto_handlers.go")
	} else {
		fmt.Println("gen no file", err)
		return
	}
	f, err := os.OpenFile(genFilePath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0660)
	if err != nil {
		fmt.Println("file", genFilePath, err)
		return
	}
	sort.Slice(v.handlers, func(i, j int) bool {
		return v.handlers[i].Proto < v.handlers[j].Proto
	})

	f.Write([]byte("// Generated by proto_handle_gen\n"))
	f.Write([]byte("package " + goPackage + "\n"))

	var imps []Imp
	for _, imp := range v.imps {
		if _, ok := v.pkgs[imp.PkgName]; ok {
			imps = append(imps, imp)
		}
	}
	fmt.Println(imps)
	importT := template.Must(template.New("import").Parse(importTmpl))
	importT.Execute(f, imps)

	funcMaps := template.FuncMap{"title": strings.Title}
	for _, h := range v.handlers {
		t := template.Must(template.New("handle").Funcs(funcMaps).Parse(handleTmpl))
		t.Execute(f, h)
	}
	regT := template.Must(template.New("register").Funcs(funcMaps).Parse(regTmpl))
	regT.Execute(f, v.handlers)

	f.Close()
}

var handleTmpl = `
func ph{{title .FuncName}}(session *menet.TcpSession, message *menet.ProtobufMessage) (msg []byte) {
	var err error
	{{if (eq .ReqType "_")}}{{else}}req := &{{.ReqType}}{}{{end}}
	resp := &{{.RespType}}{}
	{{if (eq .ReqType "_")}}{{.FuncName}}(session, nil, resp){{else}}err = proto.Unmarshal(message.Body, req)
	if err != nil {
		log.Println("proto {{.Proto}} {{.FuncName}}", err)
		return nil
	}
	{{.FuncName}}(session, req, resp){{end}}
	msg, err = proto.Marshal(resp)
	if err != nil {
		log.Println("proto {{.Proto}} {{.FuncName}}", err)
		return nil
	}
	return
}
`

var importTmpl = `
import (
	"log"
	"github.com/golang/protobuf/proto"
	"menet"
{{range . }}	{{if not (eq .Alias "")}}{{.Alias}} {{end}}"{{.Path}}"
{{end}})
`

var regTmpl = `
func RegisterProtoHandles(s *menet.TcpServer) {
	{{range . }}s.Register({{.Proto}}, ph{{title .FuncName}})
	{{end}}
}
`

func main() {
	goFile := os.Getenv("GOFILE")
	goPackage := os.Getenv("GOPACKAGE")
	goPath := os.Getenv("GOPATH")

	cwd, _ := os.Getwd()

	fs := token.NewFileSet()
	pkgs, err := parser.ParseDir(fs, cwd, nil, parser.AllErrors|parser.ParseComments)
	//f, err := parser.ParseFile(fs, goFile, nil, parser.AllErrors)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	var pkg *ast.Package
	for _, p := range pkgs {
		if strings.Contains(p.Name, "_test") == false {
			pkg = p
			break
		}
	}
	if pkg == nil {
		return
	}

	fmt.Println(goFile, goPackage, goPath)
	fmt.Println(cwd)
	//ast.Print(fs, pkg)

	phGen := &ProtoHandleGen{}
	phGen.pkgs = make(map[string]struct{})
	phGen.imps = make(map[string]Imp)
	ast.Walk(phGen, pkg)
	fmt.Println(phGen)
	phGen.Gen()
}