package template

var indexAddItem = `
	{{if gt ($indexItem.Cols|len) 1}}    
		{{if $indexItem.Unique}}    
			{{if $indexItem.Pk}}    
				_, loaded := m.hash{{$indexItem.Keys}}.LoadOrStore({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} }, cls)
				if !loaded {
			{{else}}
				m.hash{{$indexItem.Keys}}.Store({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} }, cls)
			{{end}}
		{{else}}
			if v, ok := m.hash{{$indexItem.Keys}}.LoadOrStore({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} }, &{{$.DataName}}Set{}); !ok {
				v.Store(cls, true)
			} else {
				v.Store(cls, true)
			}
		{{end}}
	{{else}}
		{{if $indexItem.Unique}}    
			{{if $indexItem.Pk}}    
				_, loaded := m.hash{{$indexItem.Keys}}.LoadOrStore(cls.{{$indexItem.Keys}}, cls)
				if !loaded {
			{{else}}
				m.hash{{$indexItem.Keys}}.Store(cls.{{$indexItem.Keys}}, cls)
			{{end}}
		{{else}}
			if v, ok := m.hash{{$indexItem.Keys}}.LoadOrStore(cls.{{$indexItem.Keys}}, &{{$.DataName}}Set{}); !ok {
				v.Store(cls, true)
			} else {
				v.Store(cls, true)
			}
		{{end}}
	{{end}}
`

var indexRemoveItem = `
	{{if gt ($indexItem.Cols|len) 1}}
		{{if $indexItem.Unique}}    
			m.hash{{$indexItem.Keys}}.Delete({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} })
		{{else}}
			if v, ok := m.hash{{$indexItem.Keys}}.Load({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} }); ok {
				v.Delete(cls)
			}
			if v, ok := m.hash{{$indexItem.Keys}}.Load({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} }); ok {
				has := false
				v.Range(func(key *{{$.DataName}}, value bool) bool {
					has = true
					return false
				})
				if !has {
					m.hash{{$indexItem.Keys}}.Delete({{$.DataName}}KeyTypeHash{{$indexItem.Keys}}{ {{$indexItem.ClsPointKeys}} })
				}
			}
		{{end}}
	{{else}}
		{{if $indexItem.Unique}}    
			m.hash{{$indexItem.Keys}}.Delete(cls.{{$indexItem.Keys}})
		{{else}}
			if v, ok := m.hash{{$indexItem.Keys}}.Load(cls.{{$indexItem.Keys}}); ok {
				v.Delete(cls)
			}
			if v, ok := m.hash{{$indexItem.Keys}}.Load(cls.{{$indexItem.Keys}}); ok {
				has := false
				v.Range(func(key *{{$.DataName}}, value bool) bool {
					has = true
					return false
				})
				if !has {
					m.hash{{$indexItem.Keys}}.Delete(cls.{{$indexItem.Keys}})
				}
			}
		{{end}}
	{{end}}
`

var Main = `// Code generated by persist. DO NOT EDIT.
// source: {{.ArgsInfo.FileName}}

package {{.PackageName}}

import (
	"github.com/go-xorm/xorm"
{{if .ArgsInfo.Save}}
	"runtime/debug"
	{{if .HashIndexPk}}    
		"reflect"
		"bytes"
		"github.com/go-xorm/core"
		"sync"
	{{else}}
		"bytes"
		"sync"
	{{end}}
	"github.com/getlantern/deepcopy"
	"menet/util"
	"os"
	"github.com/wbexwbex/queue"
	"sync/atomic"
	"encoding/json"
	"runtime"
	"time"
	"io/ioutil"
	"log"
{{end}}
	persistCore "menet/persist/core"
{{if ne .ArgsInfo.PersistPkgPath ""}}
	"{{.ArgsInfo.PersistPkgPath}}"
{{end}}
)

// 警告:
// 内部接口禁止调用(仅供内部 和 测试代码使用)
// SaveDB, DataToFailQueue, LoadFile, SaveFile, RemoveFile
// RecoverBomb, MergeQueue, AsyncSave, Collect, CheckOverload

// 需要先导入数据再使用
// 除以下接口不需要先导入, 其他接口必须 先导入! 先导入! 先导入!
// Run, Dead, Load LoadAll, Exit, Sync, SyncData(补救没有标记写回数据, 代码正确不需要使用)

// 支持 hash index:[group,unique], 不支持 tree index
// op 1:insert 2:update 3:delete 4:unload

// 待优化功能: 
// 1: 深拷贝函数 代码生成取代反射  
// 2: 环形缓冲队列避免频繁的扩大缩小  
// 3: LoadMany方法, 一次导入多个玩家数据

{{/* 定义常量 }}
const (

	// 0:初始化  1:正常运行  2:非法停止
	EPersistManagerStateIdle   = 0
	EPersistManagerStateNormal = 1
	EPersistManagerStatePanic  = 2

	// 0:导出  1:全导入开始  2:全导入完成  3:正在全导出
	EPersistTableStateDisk      = 0
	EPersistTableStateLoading   = 1
	EPersistTableStateMemory    = 2
	EPersistTableStateUnloading = 3

	// 不存在 or 0:导出  1:导入开始  2:导入完成  3:准备导出  4:正在导出
	EPersistLoadStateDisk             = 0
	EPersistLoadStateLoading          = 1
	EPersistLoadStateMemory           = 2
	EPersistLoadStatePrepareUnloading = 3
	EPersistLoadStateUnloading        = 4

	// 1:新建  2:修改  3:删除  4:导出
	EPersistOpInsert = 1
	EPersistOpUpdate = 2
	EPersistOpDelete = 3
	EPersistOpUnload = 4

	// 0:正常  1:开始退出, 清理同步队列  2:开始退出,清理缓存队列  3:写回完成
	EPersistCollectStateNormal = 0
	EPersistCollectStateSaveSync = 1
	EPersistCollectStateSaveCache = 2
	EPersistCollectStateSaveDone = 3

)
{{*/}}
const (

	// 0:初始化  1:正常运行  2:非法停止
	E{{.DataName}}ManagerStateIdle   = 0
	E{{.DataName}}ManagerStateNormal = 1
	E{{.DataName}}ManagerStatePanic  = 2

	// 0:导出  1:全导入开始  2:全导入完成  3:正在全导出
	E{{.DataName}}TableStateDisk      = 0
	E{{.DataName}}TableStateLoading   = 1
	E{{.DataName}}TableStateMemory    = 2
	E{{.DataName}}TableStateUnloading = 3

	// 不存在 or 0:导出  1:导入开始  2:导入完成  3:准备导出  4:正在导出
	E{{.DataName}}LoadStateDisk             = 0
	E{{.DataName}}LoadStateLoading          = 1
	E{{.DataName}}LoadStateMemory           = 2
	E{{.DataName}}LoadStatePrepareUnloading = 3
	E{{.DataName}}LoadStateUnloading        = 4

	// 1:新建  2:修改  3:删除  4:导出
	E{{.DataName}}OpInsert = 1
	E{{.DataName}}OpUpdate = 2
	E{{.DataName}}OpDelete = 3
	E{{.DataName}}OpUnload = 4

	// 0:正常  1:开始退出, 清理同步队列  2:开始退出,清理缓存队列  3:写回完成
	E{{.DataName}}CollectStateNormal = 0
	E{{.DataName}}CollectStateSaveSync = 1
	E{{.DataName}}CollectStateSaveCache = 2
	E{{.DataName}}CollectStateSaveDone = 3

)


{{/* 定义在其他包, 需要冲定义类型 }}
type Server = center_data.Server
{{*/}}
{{if ne .ArgsInfo.PersistPkgPath ""}}
type {{.DataName}} = {{.ArgsInfo.PersistPkgName}}.{{.DataName}}
{{end}}

{{/* 接口 DeepCopy Overload }}
{{if $.ArgsInfo.Save}}
	// persist对象必须支持并发访问, 不实现该接口默认深拷贝对象 (1 建议实现该接口,反射效率较低  2 map 建议生成syncmap  3 slice 建议深拷贝)
	type PersistDeepCopy interface {
		CopyTo(t *Persist)
	}
	// 未落地数据超过阈值时调用
	type PersistOverload interface {
		Overload(queueSize int, lastWriteBackTime time.Duration)
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// persist对象必须支持并发访问, 不实现该接口默认深拷贝对象 (1 建议实现该接口,反射效率较低  2 map 建议生成syncmap  3 slice 建议深拷贝)
	type {{.DataName}}DeepCopy interface {
		CopyTo(t *{{.DataName}})
	}
	// 未落地数据超过阈值时调用
	type {{.DataName}}Overload interface {
		Overload(queueSize int, lastWriteBackTime time.Duration)
	}
{{end}}



{{/* 生成联合索引Key结构体 }}
type PersistUidId struct {
	Uid int32
	Id  int32
}
{{*/}}
{{range $i, $v := .HashIndexList}}
	{{if gt ($v.Cols|len) 1}}
		type {{$.DataName}}{{$v.Keys}} struct {
			{{range $ii, $vv := $v.Cols }}    {{index $v.Cols $ii}} {{index $v.Types $ii}}
			{{end}}
		}
	{{end}}
{{end}}

{{/* 生成联合索引Key类型定义 }}
type PersistKeyTypeHashUidId = PersistUidId
//type PersistKeyTypeHashUid = int32
{{*/}}
{{range $i, $v := .HashIndexList}}
	{{if gt ($v.Cols|len) 1}}    type {{$.DataName}}KeyTypeHash{{$v.Keys}} = {{$.DataName}}{{$v.Keys}}
	{{else}}    type {{$.DataName}}KeyTypeHash{{$v.Keys}} = {{index $v.Types 0}}
	{{end}}
{{end}}

// {{$.DataName}}Manager 索引类型定义

{{/* 生成索引类型定义 }}
// only define type PersistHashUidId map[PersistKeyTypeHashUidId]*Persist
// only define type PersistHashUidIdMark map[PersistKeyTypeHashUidId]bool
// only define type PersistHashUid map[int32]map[*Persist]bool
{{*/}}

{{if .HashIndexPk}}    
	{{if gt (.HashIndexPk.Cols|len) 1}}    
		// only define type {{$.DataName}}Hash{{.HashIndexPk.Keys}}Mark map[{{$.DataName}}KeyTypeHash{{.HashIndexPk.Keys}}]bool
	{{else}}
		// only define type {{$.DataName}}Hash{{.HashIndexPk.Keys}}Mark map[{{index .HashIndexPk.Types 0}}]bool
	{{end}}
{{else}}

{{end}}

{{range $i, $v := .HashIndexList}}
	{{if gt ($v.Cols|len) 1}}    
		{{if $v.Unique}}    
			// only define type {{$.DataName}}Hash{{$v.Keys}} map[{{$.DataName}}KeyTypeHash{{$v.Keys}}]*{{$.DataName}}
		{{else}}
			// only define type {{$.DataName}}Hash{{$v.Keys}} map[{{$.DataName}}KeyTypeHash{{$v.Keys}}]map[*{{$.DataName}}]bool
		{{end}}
	{{else}}
		{{if $v.Unique}}    
			// only define type {{$.DataName}}Hash{{$v.Keys}} map[{{index $v.Types 0}}]*{{$.DataName}}
		{{else}}
			// only define type {{$.DataName}}Hash{{$v.Keys}} map[{{index $v.Types 0}}]map[*{{$.DataName}}]bool
		{{end}}
	{{end}}
{{end}}



// {{.DataName}}Sync 结构定义
{{/* 同步结构类型定义 }}
type PersistSync struct {
	Data *Persist
	Op   int8
}
{{*/}}
type {{.DataName}}Sync struct {
	Data *{{.DataName}}
	Op   int8
}




// {{.DataName}}Manager 结构定义

{{/* 生成索引类型定义 }}
type PersistManager struct {
{{if $.ArgsInfo.Save}}    
	// 0:初始化  1:正常运行  2:非法停止
	managerState  int32
	// 0:导出  1:全导入开始  2:全导入完成  3:正在全导出
	loadAll	      int32
	// 不存在 or 0:导出  1:导入开始  2:导入完成  3:准备导出  4:正在导出
	loadUnloadKeyMap    PersistMapUnload // map[UnloadKey]state 
	pool          *sync.Pool
	syncChan      chan *PersistSync
	syncQueue     *queue.Queue
	cacheQueue    *queue.Queue
	FailQueue     []*PersistSync
	lastWriteBackTime time.Duration
{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
	InsertQueue   []*PersistSync
{{end}}
	syncBegin     chan bool
	syncEnd       chan bool
	exitBegin     chan bool
	exitEnd       chan bool
{{end}}
	engine        *xorm.Engine
	hashUidId     PersistHashUidId 
	hashUid       PersistHashUid 
	// hashUidIdMark PersistHashUidIdMark

	{{if .ArgsInfo.OptimizeFlagIndexMutex}}
		hashStateMutex sync.RWMutex // PersistHashStateMutex
	{{end}}
}
{{*/}}
type {{.DataName}}Manager struct {
{{if $.ArgsInfo.Save}}    
	// 0:初始化  1:正常运行  2:非法停止
	managerState  int32
	// 0:导出  1:全导入开始  2:全导入完成  3:正在全导出
    loadAll       int32

	{{if .HashIndexUnload}}
		// 不存在 or 0:导出  1:导入开始  2:导入完成  3:准备导出  4:正在导出
		load{{index .HashIndexUnload.Cols 0}}Map    {{.DataName}}MapUnload // map[{{index .HashIndexUnload.Cols 0}}]state(atom) 
	{{end}}
	pool          *sync.Pool
	syncChan      chan *{{.DataName}}Sync
	syncQueue     *queue.Queue
	cacheQueue    *queue.Queue
	FailQueue     []*{{.DataName}}Sync
	lastWriteBackTime time.Duration
	{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
		InsertQueue   []*{{.DataName}}Sync
	{{end}}
	syncBegin     chan bool
	syncEnd       chan bool
	exitBegin     chan bool
	exitEnd       chan bool
{{end}}
	engine        *xorm.Engine
{{range $i, $v := .HashIndexList}}
	hash{{$v.Keys}} {{$.DataName}}Hash{{$v.Keys}}
{{end}}
{{if .HashIndexPk}}    
	// hash{{.HashIndexPk.Keys}}Mark {{$.DataName}}Hash{{.HashIndexPk.Keys}}Mark 
{{else}}

{{end}}
{{if .ArgsInfo.OptimizeFlagIndexMutex}}
	{{range $i, $v := .HashIndexList}}
		hash{{$v.Keys}}Mutex sync.RWMutex // {{$.DataName}}Hash{{$v.Keys}}Mutex
	{{end}}
{{end}}
}

{{/* reflect struct }}
var gPersistNil = &Persist{}
{{*/}}
var g{{.DataName}}Nil = &{{.DataName}}{}


{{/* new manage }}
func NewPersistManager(engine *xorm.Engine) (m *PersistManager) {
	m = &PersistManager{engine:engine}
{{if $.ArgsInfo.Save}}    
	m.syncChan = make(chan *PersistSync, runtime.NumCPU()*2)
	m.syncQueue = queue.New()
	m.syncEnd = make(chan bool)
	m.syncBegin = make(chan bool)
	m.exitBegin = make(chan bool)
	m.exitEnd = make(chan bool)
	m.cacheQueue = queue.New()
	m.lastWriteBackTime = 1 * time.Millisecond
	m.pool = &sync.Pool{New: func() interface{} { return &Persist{} }}
{{end}}
	return
}
{{*/}}
func New{{.DataName}}Manager(engine *xorm.Engine) (m *{{.DataName}}Manager) {
	m = &{{.DataName}}Manager{engine:engine}
{{if $.ArgsInfo.Save}}    
	m.syncChan = make(chan *{{.DataName}}Sync, runtime.NumCPU()*2)
	m.syncQueue = queue.New()
	m.syncEnd = make(chan bool)
	m.syncBegin = make(chan bool)
	m.exitBegin = make(chan bool)
	m.exitEnd = make(chan bool)
	m.cacheQueue = queue.New()
	m.lastWriteBackTime = 1 * time.Millisecond
	m.pool = &sync.Pool{New: func() interface{} { return &{{.DataName}}{} }}
{{end}}
	return
}

{{/* new object }}
// 通过主键创建对象, 已经存在直接返回. (1 数据没有导入或已经导出) 会返回nil. (2 数据已存在) 返回已存在的值
func NewPersist(Uid int32, Id int32) (ormCls *Persist) {
	{{if .ArgsInfo.Save}}
		{{if .HashIndexUnload}}
			if GPersistManager.LoadState(Uid) != EPersistLoadStateMemory {
				ormCls = nil
				return
			}
		{{end}}
	{{end}}

	ormCls = GPersistManager.GetPersistByUidId(Uid, Id)
	if ormCls != nil {
		return
	}

	ormCls = &Persist{Uid: Uid, Id: Id}
	_ = GPersistManager.NewPersist(ormCls)
	ormCls = GPersistManager.GetPersistByUidId(Uid, Id)
	return
}
{{*/}}
{{if .HasGlobalFuncNewPersist}}
	{{if .HashIndexPk}}
		// 通过主键创建对象, 已经存在直接返回. (1 数据没有导入或已经导出) 会返回nil. (2 数据已存在) 返回已存在的值
		func New{{.DataName}}({{.HashIndexPk.KeyTypes}}) (ormCls *{{.DataName}}) {
			{{if .ArgsInfo.Save}}
				{{if .HashIndexUnload}}
					if G{{.DataName}}Manager.LoadState({{index .HashIndexUnload.Cols 0}}) != E{{.DataName}}LoadStateMemory {
						ormCls = nil
						return
					}
				{{end}}
			{{end}}

			ormCls = G{{.DataName}}Manager.Get{{.DataName}}By{{.HashIndexPk.Keys}}( {{.HashIndexPk.CommaKeys}} )
			if ormCls != nil {
				return
			}
			ormCls = &{{.DataName}}{ {{.HashIndexPk.CommaKeyKeys}} }
			_ = G{{.DataName}}Manager.New{{.DataName}}(ormCls)
			ormCls = G{{.DataName}}Manager.Get{{.DataName}}By{{.HashIndexPk.Keys}}( {{.HashIndexPk.CommaKeys}} )
			return
		}
	{{else}}
	{{end}}
{{else}}
{{end}}




{{/* Run }}
{{if $.ArgsInfo.Save}}    
// 运行并导入上次失败数据
func (m *PersistManager) Run() error {
	if atomic.CompareAndSwapInt32(&m.managerState, EPersistManagerStateIdle, EPersistManagerStateNormal) {
		if err := m.LoadFile(); err != nil {
			return err
		}
		go m.Collect()
	} else if atomic.CompareAndSwapInt32(&m.managerState, EPersistManagerStatePanic, EPersistManagerStateNormal) {
		if err := m.LoadFile(); err != nil {
			return err
		}
		go m.Collect()
	} else {
	}
	return nil
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}    
	// 运行并导入上次失败数据
	func (m *{{.DataName}}Manager) Run() error {
		if atomic.CompareAndSwapInt32(&m.managerState, E{{.DataName}}ManagerStateIdle, E{{.DataName}}ManagerStateNormal) {
			if err := m.LoadFile(); err != nil {
				return err
			}
			go m.Collect()
		} else if atomic.CompareAndSwapInt32(&m.managerState, E{{.DataName}}ManagerStatePanic, E{{.DataName}}ManagerStateNormal) {
			if err := m.LoadFile(); err != nil {
				return err
			}
			go m.Collect()
		} else {
		}
		return nil
	}
{{else}}
	// 运行并导入上次失败数据
	func (m *{{.DataName}}Manager) Run() {
	}
{{end}}


{{/* Dead }}
{{if $.ArgsInfo.Save}}    
// 管理类是否出错
func (m *PersistManager) Dead() bool {
	return atomic.LoadInt32(&m.managerState) != EPersistManagerStateNormal
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}    
	// 管理类是否出错
	func (m *{{.DataName}}Manager) Dead() bool {
		return atomic.LoadInt32(&m.managerState) != E{{.DataName}}ManagerStateNormal
	}
{{else}}
	// 管理类是否出错
	func (m *{{.DataName}}Manager) Dead() bool {
		return true
	}
{{end}}




{{/* acquireDeepCopyObject }}
{{if $.ArgsInfo.Save}}    

	// 拷贝一个新对象用于写回
	func (m *PersistManager) acquireDeepCopyObject(cls *Persist) (ret *Persist) {
		//生成如下赋值代码
		//ret = m.pool.Get().(*Persist)
		//ret.Uid = cls.Uid
		//ret.Id = cls.Id
		//ret.State = cls.State
		//ret.Value = cls.Value
		//ret.String = cls.String
		////ret.ValueMap = cls.ValueMap
		//ret.ValueMap = make(map[int32]bool)
		//for k, v := range cls.ValueMap {
		//	ret.ValueMap[k] = v
		//}
		//ret.ValueArray = cls.ValueArray
		//ret.ValueSliceList = make([][2]int32, len(cls.ValueSliceList))
		//for i := range cls.ValueSliceList {
		//	ret.ValueSliceList[i] = cls.ValueSliceList[i]
		//}
		// _ = deepcopy.Copy(ret, cls)
		return
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}    

	// 拷贝一个新对象用于写回
	func (m *{{.DataName}}Manager) acquireDeepCopyObject(cls *{{.DataName}}) (ret *{{.DataName}}) {
		if v, ok := ((interface{})(cls)).({{.DataName}}DeepCopy); ok {
			//ret = m.pool.Get().(*{{.DataName}})
			ret = &{{.DataName}}{}
			v.CopyTo(ret)
		} else {
			ret := &{{.DataName}}{}
			_ = deepcopy.Copy(ret, cls)
			return ret
		}
		return
	}
{{end}}




{{/* releaseDeepCopyObject }}
{{if $.ArgsInfo.Save}}    
	// 释放对象
	func (m *PersistManager) releaseDeepCopyObject(cls *Persist) {
		m.pool.Put(cls)
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 释放对象
	func (m *{{.DataName}}Manager) releaseDeepCopyObject(cls *{{.DataName}}) {
		//if _, ok := ((interface{})(cls)).(*{{.DataName}}DeepCopy); ok {
		//	m.pool.Put(cls)
		//}
		return
	}
{{end}}


{{/* CheckOverload }}
	{{if $.ArgsInfo.Save}}    
		// 检查负载
		func (m *PersistManager) CheckOverload() {
			// queueLength 不是精确值,  cacheQueue, FailQueue 一写多读
			queueLength := m.cacheQueue.Length() + len(m.FailQueue)
			if queueLength > 10000 {
				if v, ok := ((interface{})(gPersistNil)).(PersistOverload); ok {
					go util.RecoverWrapFunc(func() { v.Overload(queueLength, m.lastWriteBackTime) })
				} else {
				}
			} else {
			}
		}
	{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}    
	// 检查负载
	func (m *{{.DataName}}Manager) CheckOverload() {
		// queueLength 不是精确值,  cacheQueue, FailQueue 一写多读
		queueLength := m.cacheQueue.Length() + len(m.FailQueue)
		if queueLength > {{$.ArgsInfo.QueueThreshold}} {
			if v, ok := ((interface{})(g{{.DataName}}Nil)).({{.DataName}}Overload); ok {
				go util.RecoverWrapFunc(func() { v.Overload(queueLength, m.lastWriteBackTime) })
			} else {
			}
		} else {
		}
	}
{{end}}






{{/* add }}
// 主键必须放在HashIndexList第一个
// 添加一个对象
func (m *PersistManager) addPersist(cls *Persist) bool {
	_, loaded := m.hashUidId.LoadOrStore(PersistKeyTypeHashUidId{cls.Uid, cls.Id,}, cls)
	// 不在主键中
	if !loaded {
		if _, ok := m.hashUid.Load(cls.Uid); !ok {
			m.hashUid.Store(cls.Uid, &PersistSet{})
		}
		if v, ok := m.hashUid.Load(cls.Uid); ok {
			v.Store(cls, true)
		}
	}
	return !loaded
}
{{*/}}
{{if .HashIndexPk}}
	// 添加一个对象
	func (m *{{.DataName}}Manager) add{{.DataName}}(cls *{{.DataName}}) bool {
	{{range $i, $indexItem := .HashIndexList}}
		` + indexAddItem + `
	{{end}}
		}
		return !loaded
	}
{{else}}

{{end}}


{{/* remove }}
// 删除一个对象
func (m *PersistManager) removePersist(cls *Persist) {
	m.hashUidId.Delete(PersistKeyTypeHashUidId{cls.Uid, cls.Id})
	if v, ok := m.hashUid.Load(cls.Uid); ok {
		v.Delete(cls)
	}
	if v, ok := m.hashUid.Load(cls.Uid); ok {
		has := false
		v.Range(func(key *Persist, value bool) bool {
			has = true
			return false
		})
		if !has {
			m.hashUid.Delete(cls.Uid)
		}
	}
	// m.hashUidIdMark.Delete(PersistKeyTypeHashUidId{cls.Uid, cls.Id})
	return
}
{{*/}}
{{if .HashIndexPk}}    
	// 删除一个对象
	func (m *{{.DataName}}Manager) remove{{.DataName}}(cls *{{.DataName}}) {
		{{if gt (.HashIndexPk.Cols|len) 1}}
			// m.hash{{.HashIndexPk.Keys}}Mark.Delete({{$.DataName}}KeyTypeHash{{.HashIndexPk.Keys}}{ {{.HashIndexPk.ClsPointKeys}} })
		{{else}}
			// m.hash{{.HashIndexPk.Keys}}Mark.Delete(cls.{{.HashIndexPk.Keys}})
		{{end}}

	{{range $i, $indexItem := .ReverseHashIndexList}}
		` + indexRemoveItem + `
	{{end}}
		return
	}
{{else}}

{{end}}

{{/* new }}
// 添加对象并异步写回数据库, (1 数据没有导入或已经导出, 2 数据已存在, 3 对象为空) 会返回失败
func (m *PersistManager) NewPersist(cls *Persist) error {
	{{if .ArgsInfo.Save}}
		if cls == nil {
			return persistCore.EPersistErrorNil
		}

		{{if .HashIndexUnload}}
			if m.LoadState(cls.Uid) != EPersistLoadStateMemory {
				return persistCore.EPersistErrorNotInMemory
			}
		{{end}}
	{{end}}

	{{if .ArgsInfo.OptimizeFlagIndexMutex}}
		{{range $i, $indexItem := .HashIndexList}}
			m.hash{{$indexItem.Keys}}Mutex.Lock()
			defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
		{{end}}
	{{end}}
	success := m.addPersist(cls)
{{if $.ArgsInfo.Save}}
	if success {
		m.syncChan <- &PersistSync{m.acquireDeepCopyObject(cls), EPersistOpInsert}
	} else {
		return persistCore.EPersistErrorAlreadyExist
	}
{{else}}
	if success {
	} else {
		return persistCore.EPersistErrorAlreadyExist
	}
{{end}}
	return nil
}
{{*/}}
// 添加对象并异步写回数据库, (1 数据没有导入或已经导出, 2 数据已存在, 3 对象为空) 会返回失败
func (m *{{.DataName}}Manager) New{{.DataName}}(cls *{{.DataName}}) error {

	{{if .ArgsInfo.Save}}
		if cls == nil {
			return persistCore.EPersistErrorNil
		}

		{{if .HashIndexUnload}}
			if m.LoadState(cls.{{index .HashIndexUnload.Cols 0}}) != E{{.DataName}}LoadStateMemory {
				return persistCore.EPersistErrorNotInMemory
			}
		{{end}}
	{{end}}

	{{if .HashIndexPk}}
		{{if .ArgsInfo.OptimizeFlagIndexMutex}}
			{{range $i, $indexItem := .HashIndexList}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}

		success := m.add{{.DataName}}(cls)
	{{else}}
		success := true
	{{end}}
{{if $.ArgsInfo.Save}}
	if success {
		m.syncChan <- &{{.DataName}}Sync{m.acquireDeepCopyObject(cls), E{{.DataName}}OpInsert}
	} else {
		return persistCore.EPersistErrorAlreadyExist
	}
{{else}}
	if success {
	} else {
		return persistCore.EPersistErrorAlreadyExist
	}
{{end}}
	return nil
}


{{/* delete }}
// 删除对象并异步写回数据库 (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
func (m *PersistManager) DeletePersist(cls *Persist) error {
	{{if .ArgsInfo.Save}}
		if cls == nil {
			return persistCore.EPersistErrorNil
		}
		if m.LoadState(cls.Uid) != EPersistLoadStateMemory {
			return persistCore.EPersistErrorNotInMemory
		}
	{{end}}

	p := m.GetPersistByUidId(cls.Uid, cls.Id)
	if p == nil || p != cls {
		return persistCore.EPersistErrorOutOfDate
	}

	{{if .ArgsInfo.OptimizeFlagIndexMutex}}
		{{range $i, $indexItem := .HashIndexList}}
			m.hash{{$indexItem.Keys}}Mutex.Lock()
			defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
		{{end}}
	{{end}}
	m.removePersist(cls)
{{if $.ArgsInfo.Save}}
	// 主键不能修改
	m.syncChan <- &PersistSync{cls, EPersistOpDelete}
{{end}}
	return nil
}
{{*/}}
{{if .HashIndexPk}}
	// 删除对象并异步写回数据库 (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
	func (m *{{.DataName}}Manager) Delete{{.DataName}}(cls *{{.DataName}}) error {
		if cls == nil {
			return persistCore.EPersistErrorNil
		}

		{{if .ArgsInfo.Save}}
			{{if .HashIndexUnload}}
				if m.LoadState(cls.{{index .HashIndexUnload.Cols 0}}) != E{{.DataName}}LoadStateMemory {
					return persistCore.EPersistErrorNotInMemory
				}
			{{end}}
		{{end}}

		{{if .HashIndexPk}}
			p := m.Get{{.DataName}}By{{.HashIndexPk.Keys}}({{.HashIndexPk.ClsPointKeys}})
			if p == nil || p != cls {
				return persistCore.EPersistErrorOutOfDate
			}
		{{end}}

		{{if .ArgsInfo.OptimizeFlagIndexMutex}}
			{{range $i, $indexItem := .HashIndexList}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}

		m.remove{{.DataName}}(cls)
	{{if $.ArgsInfo.Save}}
		// 主键不能修改
		m.syncChan <- &{{.DataName}}Sync{cls, E{{.DataName}}OpDelete}
	{{end}}
		return nil
	}
{{else}}

{{end}}


{{/* delete all }}
// 删除所有对象并异步写回数据库
func (m *PersistManager) DeleteAll() {
	{{if .ArgsInfo.OptimizeFlagIndexMutex}}
		{{range $i, $indexItem := .HashIndexList}}
			m.hash{{$indexItem.Keys}}Mutex.Lock()
			defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
		{{end}}
	{{end}}
	var tmpPersistList []*Persist
	m.hashUidId.Range(func(k PersistKeyTypeHashUidId, v *Persist) bool {
		tmpPersistList = append(tmpPersistList, k)
		return true
	})
	for _, cls := range tmpPersistList {
		if cls == nil {
			continue
		}
		m.removePersist(cls)
		{{if $.ArgsInfo.Save}}
			// 主键不能修改
			m.syncChan <- &PersistSync{cls, EPersistOpDelete}
		{{end}}
	}
}
{{*/}}
{{if .HashIndexPk}}    
	// 删除所有对象并异步写回数据库
	func (m *{{.DataName}}Manager) DeleteAll() {
		{{if .ArgsInfo.OptimizeFlagIndexMutex}}
			{{range $i, $indexItem := .HashIndexList}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}
		var tmp{{.DataName}}List []*{{.DataName}}
		m.hash{{.HashIndexPk.Keys}}.Range(func(k {{.DataName}}KeyTypeHash{{.HashIndexPk.Keys}}, v *{{.DataName}}) bool {
			tmp{{.DataName}}List = append(tmp{{.DataName}}List, v)
			return true
		})
		for _, cls := range tmp{{.DataName}}List {
			if cls == nil {
				continue
			}
			m.remove{{.DataName}}(cls)
			{{if $.ArgsInfo.Save}}
				// 主键不能修改
				m.syncChan <- &{{.DataName}}Sync{cls, E{{.DataName}}OpDelete}
			{{end}}
		}
	}
{{else}}

{{end}}


{{/* delete 非主键的索引列修改,必须用set方法}}
只删除相关连的索引, 修改索引时, 上锁
// 修改包含索引字段, 标记脏对象并异步写回数据库, 需要保证一致性, 生成时开启 EOptimizeFlagIndexMutex
// (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
func (m *PersistManager) SetIndexKeyState(cls *Persist, State int32, ) error {
	{{if .ArgsInfo.OptimizeFlagIndexMutex}}
		m.hashStateMutex.Lock()
		defer m.hashStateMutex.Unlock()
	{{end}}
	if cls == nil {
		return persistCore.EPersistErrorNil
	}
	if v, ok := m.hashState.Load(cls.State); ok {
		v.Delete(cls)
	}
	cls.State = State
	if v, ok := m.hashState.LoadOrStore(cls.State, &PersistSet{}); !ok {
		v.Store(cls, true)
	} else {
		v.Store(cls, true)
	}
	return m.MarkUpdate(cls)
}
{{*/}}
// 不建议修改索引列
{{range $i, $v := .ModifyHashIndexList}}
	// 修改包含索引字段, 标记脏对象并异步写回数据库, 需要保证一致性, 生成时开启 EOptimizeFlagIndexMutex
	// (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
	func (m *{{$.DataName}}Manager) SetIndexKey{{$v.Keys}}(cls *{{$.DataName}}, {{$v.KeyTypesStripPk}} ) error {
		{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
			// 需要按照顺序上锁
			{{range $ii, $indexItem := $v.EffectIndex}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}
		if cls == nil {
			return persistCore.EPersistErrorNil
		}
		{{range $ii, $indexItem := $v.EffectIndex}}
			` + indexRemoveItem + `
		{{end}}

		{{range $iEffect, $vEffect := $v.KeysStripPk}}
			cls.{{$vEffect}} = {{$vEffect}}
		{{end}}

		{{range $ii, $indexItem := $v.EffectIndex}}
			` + indexAddItem + `
		{{end}}
		return m.MarkUpdate(cls)
	}
{{end}}

{{range $i, $col := .ModifyColList}}
	// 修改包含索引字段, 标记脏对象并异步写回数据库, 需要保证一致性, 生成时开启 EOptimizeFlagIndexMutex
	// (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
	func (m *{{$.DataName}}Manager) SetIndexKey{{$col}}(cls *{{$.DataName}}, {{$col}} {{index $.KeyTypeMap $col}} ) error {
		{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
			// 需要按照顺序上锁
			{{range $ii, $indexItem := index $.ColEffectHashMap $col}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}
		if cls == nil {
			return persistCore.EPersistErrorNil
		}
		{{range $ii, $indexItem := index $.ColEffectHashMap $col}}
			` + indexRemoveItem + `
		{{end}}

		cls.{{$col}} = {{$col}}

		{{range $ii, $indexItem := index $.ColEffectHashMap $col}}
			` + indexAddItem + `
		{{end}}
		return m.MarkUpdate(cls)
	}
{{end}}


{{/* mark update }}
// 标记脏对象并异步写回数据库, (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
func (m *PersistManager) MarkUpdate(cls *Persist) error {

	if cls == nil {
		return persistCore.EPersistErrorNil
	}
	{{if .ArgsInfo.Save}}
		if m.LoadState(cls.Uid) != EPersistLoadStateMemory {
			return persistCore.EPersistErrorNotInMemory
		}
	{{end}}

	p := m.GetPersistByUidId(cls.Uid, cls.Id)
	if p == nil || p != cls {
		return persistCore.EPersistErrorOutOfDate
	}

{{if $.ArgsInfo.Save}}
	m.syncChan <- &PersistSync{m.acquireDeepCopyObject(cls), EPersistOpUpdate}
{{end}}
	return nil
}
{{*/}}
// 标记脏对象并异步写回数据库, (1 数据没有导入或已经导出, 2 数据已经重新导入, 3 对象为空) 会返回失败
func (m *{{.DataName}}Manager) MarkUpdate(cls *{{.DataName}}) error {
	if cls == nil {
		return persistCore.EPersistErrorNil
	}
	{{if .ArgsInfo.Save}}
		{{if .HashIndexUnload}}
			if m.LoadState(cls.{{index .HashIndexUnload.Cols 0}}) != E{{.DataName}}LoadStateMemory {
				return persistCore.EPersistErrorNotInMemory
			}
		{{end}}
	{{end}}

	{{if .HashIndexPk}}
		p := m.Get{{.DataName}}By{{.HashIndexPk.Keys}}({{.HashIndexPk.ClsPointKeys}})
		if p == nil || p != cls {
			return persistCore.EPersistErrorOutOfDate
		}
	{{end}}

{{if $.ArgsInfo.Save}}
	m.syncChan <- &{{.DataName}}Sync{m.acquireDeepCopyObject(cls), E{{.DataName}}OpUpdate}
{{end}}
	return nil
}


{{/* get }}
// 通过索引查找对象
func (m *PersistManager) GetPersistByUidId(Uid int32, Id int32) (*Persist) {
	{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
		// 需要按照顺序上锁
		{{range $ii, $indexItem := $v.EffectIndex}}
			m.hash{{$indexItem.Keys}}Mutex.RLock()
			defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
		{{end}}
	{{end}}
	if data, ok := m.hashUidId.Load(PersistKeyTypeHashUidId{Uid, Id}); ok {
		return data
	}
	return nil
}
// 通过索引查找对象
func (m *PersistManager) GetPersistsByUid(Uid int32) (ret []*Persist) {
	{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
		// 需要按照顺序上锁
		{{range $ii, $indexItem := $v.EffectIndex}}
			m.hash{{$indexItem.Keys}}Mutex.RLock()
			defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
		{{end}}
	{{end}}
	if data, ok := m.hashUid.Load(Uid); ok {
		data.Range(func(k *Persist, v bool) bool {
			ret = append(ret, k)
			return true
		})
	}
	return
}
{{*/}}
{{range $i, $v := .HashIndexList}}
	{{if gt ($v.Cols|len) 1}}
		{{if $v.Unique}}    
			// 通过索引查找对象
			func (m *{{$.DataName}}Manager) Get{{$.DataName}}By{{$v.Keys}}({{$v.KeyTypes}}) (*{{$.DataName}}) {
				{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
					// 需要按照顺序上锁, 主键不允许修改不需要上锁
					{{range $ii, $indexItem := $v.EffectIndex}}
						m.hash{{$indexItem.Keys}}Mutex.RLock()
						defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
					{{end}}
				{{end}}
				if data, ok := m.hash{{$v.Keys}}.Load({{$.DataName}}KeyTypeHash{{$v.Keys}}{ {{$v.CommaKeys}} }); ok {
					return data
				}
				return nil
			}
		{{else}}
			// 通过索引查找对象
			func (m *{{$.DataName}}Manager) Get{{$.DataName}}sBy{{$v.Keys}}({{$v.KeyTypes}}) (ret []*{{$.DataName}}) {
				{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
					// 需要按照顺序上锁, 主键不允许修改不需要上锁
					{{range $ii, $indexItem := $v.EffectIndex}}
						m.hash{{$indexItem.Keys}}Mutex.RLock()
						defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
					{{end}}
				{{end}}
				if data, ok := m.hash{{$v.Keys}}.Load({{$.DataName}}KeyTypeHash{{$v.Keys}}{ {{$v.CommaKeys}} }); ok {
					data.Range(func(k *{{$.DataName}}, v bool) bool {
						ret = append(ret, k)
						return true
					})
				}
				return
			}
		{{end}}
	{{else}}
		{{if $v.Unique}}    
			// 通过索引查找对象
			func (m *{{$.DataName}}Manager) Get{{$.DataName}}By{{$v.Keys}}({{$v.KeyTypes}}) (*{{$.DataName}}) {
				{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
					// 需要按照顺序上锁, 主键不允许修改不需要上锁
					{{range $ii, $indexItem := $v.EffectIndex}}
						m.hash{{$indexItem.Keys}}Mutex.RLock()
						defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
					{{end}}
				{{end}}
				if data, ok := m.hash{{$v.Keys}}.Load({{$v.Keys}}); ok {
					return data
				}
				return nil
			}
		{{else}}
			// 通过索引查找对象
			func (m *{{$.DataName}}Manager) Get{{$.DataName}}sBy{{$v.Keys}}({{$v.KeyTypes}}) (ret []*{{$.DataName}}) {
				{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
					// 需要按照顺序上锁, 主键不允许修改不需要上锁
					{{range $ii, $indexItem := $v.EffectIndex}}
						m.hash{{$indexItem.Keys}}Mutex.RLock()
						defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
					{{end}}
				{{end}}
				if data, ok := m.hash{{$v.Keys}}.Load({{$v.Keys}}); ok {
					data.Range(func(k *{{$.DataName}}, v bool) bool {
						ret = append(ret, k)
						return true
					})
				}
				return
			}
		{{end}}
	{{end}}
{{end}}


{{/* get all }}
// 通过主键查找所有对象
func (m *PersistManager) GetAll() (ret []*Persist) {
     // 这里的锁其实是多余的
	{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
		// 需要按照顺序上锁
		{{range $ii, $indexItem := .HashIndexList}}
			m.hash{{$indexItem.Keys}}Mutex.RLock()
			defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
		{{end}}
	{{end}}
	m.hashUidId.Range(func(k PersistKeyTypeHashUidId, v *Persist) bool {
		ret = append(ret, v)
		return true
	})
	return
}
{{*/}}
{{if .HashIndexPk}}    
	// 通过主键查找所有对象
	func (m *{{.DataName}}Manager) GetAll() (ret []*{{.DataName}}) {
		{{if $.ArgsInfo.OptimizeFlagIndexMutex}}
			// 需要按照顺序上锁
			{{range $ii, $indexItem := .HashIndexList}}
				m.hash{{$indexItem.Keys}}Mutex.RLock()
				defer m.hash{{$indexItem.Keys}}Mutex.RUnlock()
			{{end}}
		{{end}}
		m.hash{{.HashIndexPk.Keys}}.Range(func(k {{.DataName}}KeyTypeHash{{.HashIndexPk.Keys}}, v *{{.DataName}}) bool {
			ret = append(ret, v)
			return true
		})
		return
	}
{{else}}

{{end}}

{{/* LoadAllState }}
{{if $.ArgsInfo.Save}}
	// 所有数据导入状态
	func (m *PersistManager) LoadAllState() int32 {
		return atomic.LoadInt32(&m.loadAll)
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 所有数据导入状态
	func (m *{{.DataName}}Manager) LoadAllState() int32 {
		return atomic.LoadInt32(&m.loadAll)
	}
{{end}}


{{/* loadAll }}
{{if $.ArgsInfo.Save}}
	// (非线程安全) 导入所有数据, 全导入后只能全导出, 不能再按照key导入导出
	func (m *PersistManager) LoadAll() (err error) {
		// 未全导入状态切换到全导入
		if atomic.CompareAndSwapInt32(&m.loadAll, EPersistTableStateDisk, EPersistTableStateLoading){
			rows := make([]*Persist, 0)
			err = m.engine.Find(&rows, gPersistNil)
			if err != nil {
				atomic.StoreInt32(&m.loadAll, EPersistTableStateDisk)
				return err
			} else {
				{{if .ArgsInfo.OptimizeFlagIndexMutex}}
					{{range $i, $indexItem := .HashIndexList}}
						m.hash{{$indexItem.Keys}}Mutex.Lock()
						defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
					{{end}}
				{{end}}
				for _, row := range rows{
					m.addPersist(row)
				}
				atomic.StoreInt32(&m.loadAll, EPersistTableStateMemory)
			}
		} else {
			return persistCore.EPersistErrorIncorrectState
		}
		return
	}
	{{end}}
{{*/}}
{{if .HashIndexPk}}
	{{if $.ArgsInfo.Save}}
		// (非线程安全) 导入所有数据, 全导入后只能全导出, 不能再按照key导入导出
		func (m *{{.DataName}}Manager) LoadAll() (err error) {
			// 未全导入状态切换到全导入
			if atomic.CompareAndSwapInt32(&m.loadAll, E{{.DataName}}TableStateDisk, E{{.DataName}}TableStateLoading){
				rows := make([]*{{.DataName}}, 0)
				err = m.engine.Find(&rows, g{{.DataName}}Nil)
				if err != nil {
					atomic.StoreInt32(&m.loadAll, E{{.DataName}}TableStateDisk)
					return err
				} else {
					{{if .ArgsInfo.OptimizeFlagIndexMutex}}
						{{range $i, $indexItem := .HashIndexList}}
							m.hash{{$indexItem.Keys}}Mutex.Lock()
							defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
						{{end}}
					{{end}}
					for _, row := range rows {
						m.add{{.DataName}}(row)
					}
					atomic.StoreInt32(&m.loadAll, E{{.DataName}}TableStateMemory)
				}
			} else {
				return persistCore.EPersistErrorIncorrectState
			}
			return
		}
	{{end}}
{{else}}

{{end}}

{{/* LoadState }}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// 查询包含该key的数据导入状态
	func (m *PersistManager) LoadState(Uid int32) int32 {
		if atomic.LoadInt32(&m.loadAll) == EPersistTableStateDisk {
			if value, ok := m.loadUidMap.Load(Uid); ok {
				state := value
				return atomic.LoadInt32(state)
			} else {
				return EPersistLoadStateDisk
			}
		} else {
			return EPersistLoadStateMemory
		}
	}
{{end}}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// 查询包含该key的数据导入状态
	func (m *{{.DataName}}Manager) LoadState({{index .HashIndexUnload.Cols 0}} {{index .HashIndexUnload.Types 0}}) int32 {
		if atomic.LoadInt32(&m.loadAll) == E{{.DataName}}TableStateDisk {
			if value, ok := m.load{{index .HashIndexUnload.Cols 0}}Map.Load({{index .HashIndexUnload.Cols 0}}); ok {
				state := value
				return atomic.LoadInt32(state)
			} else {
				return E{{.DataName}}LoadStateDisk
			}
		} else {
			return E{{.DataName}}LoadStateMemory
		}
	}
{{end}}
{{end}}


{{/* SetLoadState2Memory }}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// 没有数据时, 标记数据在内存中. 仅用于第一次数据库导入空数据, 错误使用会导致未定义的行为
	func (m *PersistManager) SetLoadState2Memory(Uid int32) {
		if atomic.LoadInt32(&m.loadAll) == EPersistTableStateDisk {
			p := int32(EPersistLoadStateMemory)
			m.loadUidMap.Store(Uid, &p)
		} else {
		}
	}
{{end}}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// 没有数据时, 标记数据在内存中. 仅用于第一次数据库导入空数据, 错误使用会导致未定义的行为
	func (m *{{.DataName}}Manager) SetLoadState2Memory({{index .HashIndexUnload.Cols 0}} {{index .HashIndexUnload.Types 0}}) {
		if atomic.LoadInt32(&m.loadAll) == E{{.DataName}}TableStateDisk {
			p := int32(E{{.DataName}}LoadStateMemory)
			m.load{{index .HashIndexUnload.Cols 0}}Map.Store({{index .HashIndexUnload.Cols 0}}, &p)
		} else {
		}
	}
{{end}}
{{end}}


{{/* load }}
{{if $.ArgsInfo.Save}}
	// 按照key导入数据, 必须存在unload key的索引
	func (m *PersistManager) Load(UnloadKey UnloadKeyType) (err error) {
		// return 不存在unload key时直接返回
		// LoadAll后不能再次Load
		if atomic.LoadInt32(&m.loadAll) == EPersistTableStateDisk {
			p := int32(0)
			value, _ := m.loadUidMap.LoadOrStore(Uid, &p)
			state := value
			// 检查导入状态
			switch atomic.LoadInt32(state) {
			// 未导入状态切换到导入
			case EPersistLoadStateDisk:
				if atomic.CompareAndSwapInt32(state, EPersistLoadStateDisk, EPersistLoadStateLoading) {
					rows := make([]*Persist, 0)
					err = m.engine.Find(&rows, &Persist{Uid: Uid})
					if err != nil { // 导入失败, 状态回到导出
						atomic.StoreInt32(state, EPersistLoadStateDisk)
					} else {
						for _, row := range rows{
							m.addPersist(row)
						}
						atomic.StoreInt32(state, EPersistLoadStateMemory)
					}
					return
				} else { // 期间状态变化,不确定操作是否成功
					return persistCore.EPersistErrorUnknownError
				}

			case EPersistLoadStateLoading: // 正在导入
				// 并发导入暂时轮询等待
				bTime := time.Now().Unix()
				for {
					if atomic.LoadInt32(state) != EPersistLoadStateLoading {
						break
					}
					if time.Now().Unix() > bTime+persistCore.ELoadPollingTimeOut {
						break
					}
					time.Sleep(time.Millisecond * 100)
				}
				if atomic.LoadInt32(state) == EPersistLoadStateMemory {
					return
				} else {
					return persistCore.EPersistErrorUnknownError
				}

			case EPersistLoadStateMemory: // 导入完成
				return

			case EPersistLoadStatePrepareUnloading: // 准备导出,立即取消导出
				if atomic.CompareAndSwapInt32(state, EPersistLoadStatePrepareUnloading, EPersistLoadStateMemory) {
					return
				} else { // 期间状态变化,不确定操作是否成功
					return persistCore.EPersistErrorUnknownError
				}
			case EPersistLoadStateUnloading: // 正在导出
				return persistCore.EPersistErrorUnloading
			default: // ???
				return persistCore.EPersistErrorUnknownError
			}
		} else {
			return
		}
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// 按照key导入数据, 必须存在unload key的索引
	func (m *{{.DataName}}Manager) Load({{index .HashIndexUnload.Cols 0}} {{index .HashIndexUnload.Types 0}}) (err error) {
		// LoadAll后不能再次Load
		if atomic.LoadInt32(&m.loadAll) == E{{.DataName}}TableStateDisk {
			p := int32(0)
			value, _ := m.load{{index .HashIndexUnload.Cols 0}}Map.LoadOrStore({{index .HashIndexUnload.Cols 0}}, &p)
			state := value
			// 检查导入状态
			switch atomic.LoadInt32(state) {
			// 未导入状态切换到导入
			case E{{.DataName}}LoadStateDisk:
				if atomic.CompareAndSwapInt32(state, E{{.DataName}}LoadStateDisk, E{{.DataName}}LoadStateLoading) {
					rows := make([]*{{.DataName}}, 0)
					err = m.engine.Find(&rows, &{{.DataName}}{ {{index .HashIndexUnload.Cols 0}}: {{index .HashIndexUnload.Cols 0}} })

					if err != nil { // 导入失败, 状态回到导出
						atomic.StoreInt32(state, E{{.DataName}}LoadStateDisk)
					} else {
						{{if .ArgsInfo.OptimizeFlagIndexMutex}}
							{{range $i, $indexItem := .HashIndexList}}
								m.hash{{$indexItem.Keys}}Mutex.Lock()
								defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
							{{end}}
						{{end}}
						for _, row := range rows{
							m.add{{.DataName}}(row)
						}
						atomic.StoreInt32(state, E{{.DataName}}LoadStateMemory)
					}
					return
				} else { // 期间状态变化,不确定操作是否成功
					return persistCore.EPersistErrorUnknownError
				}

			case E{{.DataName}}LoadStateLoading: // 正在导入
				// 并发导入暂时轮询等待
				bTime := time.Now().Unix()
				for {
					if atomic.LoadInt32(state) != E{{.DataName}}LoadStateLoading {
						break
					}
					if time.Now().Unix() > bTime+persistCore.ELoadPollingTimeOut {
						break
					}
					time.Sleep(time.Millisecond * 100)
				}
				if atomic.LoadInt32(state) == E{{.DataName}}LoadStateMemory {
					return
				} else {
					return persistCore.EPersistErrorUnknownError
				}

			case E{{.DataName}}LoadStateMemory: // 导入完成
				return

			case E{{.DataName}}LoadStatePrepareUnloading: // 准备导出,立即取消导出
				if atomic.CompareAndSwapInt32(state, E{{.DataName}}LoadStatePrepareUnloading, E{{.DataName}}LoadStateMemory) {
					return
				} else { // 期间状态变化,不确定操作是否成功
					return persistCore.EPersistErrorUnknownError
				}

			case E{{.DataName}}LoadStateUnloading: // 正在导出
				return persistCore.EPersistErrorUnloading
			default: // ???
				return persistCore.EPersistErrorUnknownError
			}
		} else {
			return
		}
	}
{{end}}
{{end}}



{{/* UnloadAll }}
{{if $.ArgsInfo.Save}}
	// (非线程安全) 导出所有数据, 调用UnloadAll后,不允许再修改相关的数据(必须先导入才能修改数据)
	func (m *PersistManager) UnloadAll() (err error) {
		var clsList []*Persist
		// 未导入状态切换到导入
		if atomic.CompareAndSwapInt32(&m.loadAll, EPersistTableStateMemory, EPersistTableStateUnloading) {
			{{if .ArgsInfo.OptimizeFlagIndexMutex}}
				{{range $i, $indexItem := .HashIndexList}}
					m.hash{{$indexItem.Keys}}Mutex.Lock()
					defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
				{{end}}
			{{end}}
			m.hashUidId.Range(func(k PersistKeyTypeHashUidId, v *Persist) bool {
				clsList = append(clsList, v)
				return true
			})
			for _, cls := range clsList {
				m.removePersist(cls)
			}
			atomic.StoreInt32(&m.loadAll, EPersistTableStateDisk)
		} else {
			return persistCore.EPersistErrorIncorrectState
		}
		return
	}
{{end}}
{{*/}}

{{if .HashIndexPk}}
{{if $.ArgsInfo.Save}}
	// (非线程安全) 导出所有数据, 调用UnloadAll后,不允许再修改相关的数据(必须先导入才能修改数据)
	func (m *{{.DataName}}Manager) UnloadAll() (err error) {
		var clsList []*{{.DataName}}
		// 未导入状态切换到导入
		if atomic.CompareAndSwapInt32(&m.loadAll, E{{.DataName}}TableStateMemory, E{{.DataName}}TableStateUnloading) {
			{{if .ArgsInfo.OptimizeFlagIndexMutex}}
				{{range $i, $indexItem := .HashIndexList}}
					m.hash{{$indexItem.Keys}}Mutex.Lock()
					defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
				{{end}}
			{{end}}
			m.hash{{.HashIndexPk.Keys}}.Range(func(k {{.DataName}}KeyTypeHash{{.HashIndexPk.Keys}}, v *{{.DataName}}) bool {
				clsList = append(clsList, v)
				return true
			})
			for _, cls := range clsList {
				m.remove{{.DataName}}(cls)
			}
			atomic.StoreInt32(&m.loadAll, E{{.DataName}}TableStateDisk)
		} else {
			return persistCore.EPersistErrorIncorrectState
		}
		return
	}
{{end}}
{{else}}

{{end}}




{{/* Unload }}
{{if $.ArgsInfo.Save}}
	// 按照key导出数据, 必须存在unload key的索引. 调用Unload后,不允许再修改相关的数据(必须先导入才能修改数据).
	func (m *PersistManager) Unload(UnloadKey UnloadKeyType) (err error) {
		{{if $.ArgsInfo.Unload}}
			// return 不存在unload key时直接返回
			// LoadAll后不能unload
			if atomic.LoadInt32(&m.loadAll) == EPersistTableStateDisk {
				if value, ok := m.loadUnloadKeyMap.Load(UnloadKey); ok {
					state := value
					switch atomic.LoadInt32(state) {
					case EPersistLoadStateDisk: // 未导入
						return //persistCore.EPersistErrorNotInMemory
					case EPersistLoadStateLoading: // 正在导入
						return persistCore.EPersistErrorLoading
					case EPersistLoadStateMemory: // 导入完成, 开始导出吧
						if atomic.CompareAndSwapInt32(state, EPersistLoadStateMemory, EPersistLoadStatePrepareUnloading) {
							m.syncChan <- &PersistSync{&Persist{Uid: Uid}, EPersistOpUnload}
							return
						} else { // 期间状态变化,不确定操作是否成功
							return persistCore.EPersistErrorUnknownError
						}
					case EPersistLoadStatePrepareUnloading: // 准备导出, 立即取消导出
						return //persistCore.EPersistErrorAlreadyUnload
					case EPersistLoadStateUnloading: // 正在导出, 导入失败
						return //persistCore.EPersistErrorUnloading
					default:
						return persistCore.EPersistErrorUnknownError
					}
				} else {
					return //persistCore.EPersistErrorNotInMemory
				}
			} else {
				return persistCore.EPersistErrorAlreadyLoadAll
			}
		{{else}}
			return
		{{end}}
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// 按照key导出数据, 必须存在unload key的索引. 调用Unload后,不允许再修改相关的数据(必须先导入才能修改数据).
	func (m *{{.DataName}}Manager) Unload({{index .HashIndexUnload.Cols 0}} {{index .HashIndexUnload.Types 0}}) (err error) {
		{{if $.ArgsInfo.Unload}}

			// LoadAll后不能unload
			if atomic.LoadInt32(&m.loadAll) == E{{.DataName}}TableStateDisk {
				if value, ok := m.load{{index .HashIndexUnload.Cols 0}}Map.Load({{index .HashIndexUnload.Cols 0}}); ok {
					state := value

					switch atomic.LoadInt32(state) {
					case E{{.DataName}}LoadStateDisk: // 未导入
						return //persistCore.EPersistErrorNotInMemory
					case E{{.DataName}}LoadStateLoading: // 正在导入
						return persistCore.EPersistErrorLoading
					case E{{.DataName}}LoadStateMemory: // 导入完成, 开始导出吧
						if atomic.CompareAndSwapInt32(state, E{{.DataName}}LoadStateMemory, E{{.DataName}}LoadStatePrepareUnloading) {
							m.syncChan <- &{{.DataName}}Sync{&{{.DataName}}{ {{index .HashIndexUnload.Cols 0}}: {{index .HashIndexUnload.Cols 0}} }, E{{.DataName}}OpUnload}
							return
						} else { // 期间状态变化,不确定操作是否成功
							return persistCore.EPersistErrorUnknownError
						}
					case E{{.DataName}}LoadStatePrepareUnloading: // 准备导出, 立即取消导出
						return //persistCore.EPersistErrorAlreadyUnload
					case E{{.DataName}}LoadStateUnloading: // 正在导出, 导入失败
						return //persistCore.EPersistErrorUnloading
					default:
						return persistCore.EPersistErrorUnknownError
					}
				} else {
					return //persistCore.EPersistErrorNotInMemory
				}
			} else {
				return persistCore.EPersistErrorAlreadyLoadAll
			}
		{{else}}
			return
		{{end}}
	}
{{end}}
{{end}}



{{/* unload }}
{{if $.ArgsInfo.Save}}
	// (非线程安全) 按照key导出数据, 必须存在unload key的索引. 调用Unload后,不允许再修改相关的数据(必须先导入才能修改数据).
	func (m *PersistManager) unload(UnloadKey UnloadKeyType) {
		{{if .ArgsInfo.OptimizeFlagIndexMutex}}
			{{range $i, $indexItem := .HashIndexList}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}
		// 不存在unload key 索引什么都不干
		// unload key unique = 0
		for _, cls := range m.GetPersistsByUnloadKey(UnloadKey) {
			m.removePersist(cls)
		}
		// unload key unique = 1
		//cls := m.GetPersistByUnloadKey(UnloadKey)
		//if cls != nil {
		//	m.removePersist(cls)
		//}
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
{{if .HashIndexUnload}}
	// (非线程安全) 按照key导出数据, 必须存在unload key的索引. 调用Unload后,不允许再修改相关的数据(必须先导入才能修改数据).
	func (m *{{.DataName}}Manager) unload({{index .HashIndexUnload.Cols 0}} {{index .HashIndexUnload.Types 0}}) {
		{{if .ArgsInfo.OptimizeFlagIndexMutex}}
			{{range $i, $indexItem := .HashIndexList}}
				m.hash{{$indexItem.Keys}}Mutex.Lock()
				defer m.hash{{$indexItem.Keys}}Mutex.Unlock()
			{{end}}
		{{end}}
		{{if .HashIndexUnload.Unique}}
			cls := m.Get{{.DataName}}By{{index .HashIndexUnload.Cols 0}}({{index .HashIndexUnload.Cols 0}})
			if cls != nil {
				m.remove{{.DataName}}(cls)
			}
		{{else}}
			for _, cls := range m.Get{{.DataName}}sBy{{index .HashIndexUnload.Cols 0}}({{index .HashIndexUnload.Cols 0}}) {
				m.remove{{.DataName}}(cls)
			}
		{{end}}
	}
{{end}}
{{end}}







{{/* init global manage }}
var GPersistManager *PersistManager
// 注册管理类
func init() {
	engine := GetDB()
	if engine == nil {
		panic(persistCore.EPersistErrorEngineNil)
	}
	GPersistManager = NewPersistManager(engine)
{{if $.ArgsInfo.Save}}
	Register("Persist", GPersistManager)
	// go GPersistManager.Collect()
{{end}}
}
{{*/}}
var G{{.DataName}}Manager *{{.DataName}}Manager
// 注册管理类
func init() {
	engine := GetDB()
	if engine == nil {
		panic(persistCore.EPersistErrorEngineNil)
	}
	G{{.DataName}}Manager = New{{.DataName}}Manager(engine)
{{if $.ArgsInfo.Save}}
	Register("{{.DataName}}", G{{.DataName}}Manager)
	// go G{{.DataName}}Manager.Collect()
{{end}}
}


{{/* SaveDB }}
{{if $.ArgsInfo.Save}}
// xorm写数据库
func (m *PersistManager) SaveDB(session *xorm.Session, persistSync *PersistSync) (err error) {
	switch persistSync.Op {
	case EPersistOpInsert:
		_, err = session.Insert(persistSync.Data)
		if err != nil {
			log.Println("insert error ", err, "[sql error]", persistSync.Data)
			return
		}
	case EPersistOpUpdate:
		cls := persistSync.Data
		_, err = session.ID(core.NewPK(cls.Uid, cls.Id, )).AllCols().Update(cls)
		if err != nil {
			log.Println("update error ", err, "[sql error]", persistSync.Data)
			return
		}
	case EPersistOpDelete:
		cls := persistSync.Data
		_, err = session.ID(core.NewPK(cls.Uid, cls.Id, )).Delete(gPersistNil)
		if err != nil {
			log.Println("delete error ", err, "[sql error]", persistSync.Data)
			return
		}
	case EPersistOpUnload:
		cls := persistSync.Data
		Uid := cls.Uid
		if value, ok := m.loadUidMap.Load(Uid); ok {
			state := value
			// 准备导出,  不中断的清理玩家数据
			// warning 导出后又修改, 不保证数据一致性
			if atomic.CompareAndSwapInt32(state, EPersistLoadStatePrepareUnloading, EPersistLoadStateUnloading) {
				m.unload(Uid)
				atomic.StoreInt32(state, EPersistLoadStateDisk)
				m.loadUidMap.Delete(Uid)
			} else {
				// 0:导出  1:导入开始  2:导入完成  4:正在导出  不确定状态
				// 以上状态跳过吧
			}
		} else {
			// 不存在的玩家,跳过吧
		}
	}
	return
}
{{end}}

{{*/}}
{{if $.ArgsInfo.Save}}
	// xorm写数据库
	func (m *{{.DataName}}Manager) SaveDB(session *xorm.Session, persistSync *{{.DataName}}Sync) (err error) {
		switch persistSync.Op {
		case E{{.DataName}}OpInsert:
			_, err = session.Insert(persistSync.Data)
			if err != nil {
				log.Println("insert error ", err, "[sql error]", persistSync.Data)
				return
			}
		{{if .HashIndexPk}}
			case E{{.DataName}}OpUpdate:
				cls := persistSync.Data
				_, err = session.ID(core.NewPK({{.HashIndexPk.ClsPointKeys}})).AllCols().Update(cls)
				if err != nil {
					log.Println("update error ", err, "[sql error]", persistSync.Data)
					return
				}
			case E{{.DataName}}OpDelete:
				cls := persistSync.Data
				_, err = session.ID(core.NewPK({{.HashIndexPk.ClsPointKeys}})).Delete(g{{.DataName}}Nil)
				if err != nil {
					log.Println("delete error ", err, "[sql error]", persistSync.Data)
					return
				}
			{{if .HashIndexUnload}}
				case E{{.DataName}}OpUnload:
					cls := persistSync.Data
					{{index .HashIndexUnload.Cols 0}} := cls.{{index .HashIndexUnload.Cols 0}}
					if value, ok := m.load{{index .HashIndexUnload.Cols 0}}Map.Load({{index .HashIndexUnload.Cols 0}}); ok {
						state := value
						// 准备导出,  不中断的清理玩家数据
						// warning 导出后又修改, 不保证数据一致性
						if atomic.CompareAndSwapInt32(state, E{{.DataName}}LoadStatePrepareUnloading, E{{.DataName}}LoadStateUnloading) {
							m.unload({{index .HashIndexUnload.Cols 0}})
							atomic.StoreInt32(state, E{{.DataName}}LoadStateDisk)
							m.load{{index .HashIndexUnload.Cols 0}}Map.Delete({{index .HashIndexUnload.Cols 0}})
						} else {
							// 0:导出  1:导入开始  2:导入完成  4:正在导出  不确定状态
							// 以上状态跳过吧
						}
					} else {
						// 不存在的玩家,跳过吧
					}
			{{end}}
		{{else}}

		{{end}}
		}
		return
	}
{{end}}


{{/* DataToFailQueue }}
{{if $.ArgsInfo.Save}}
// 未写入成功数据, 添加到失败队列
func (m *PersistManager) DataToFailQueue() {
	var persistSync *PersistSync
	// 一旦失败标记所有的数据都是失败, 不允许导出

	m.FailQueue = append(m.FailQueue, m.InsertQueue...)
	m.InsertQueue = m.InsertQueue[0:0]

	for i := m.syncQueue.Length(); i > 0; i-- {
		persistSync = m.syncQueue.Remove().(*PersistSync)
		switch persistSync.Op {
		case EPersistOpInsert, EPersistOpUpdate, EPersistOpDelete:
			m.FailQueue = append(m.FailQueue, persistSync)
		case EPersistOpUnload:
			// 导出状态还原
			cls := persistSync.Data
			Uid := cls.Uid
			if value, ok := m.loadUidMap.Load(Uid); ok {
				state := value
				// 导出失败状态回退
				if atomic.CompareAndSwapInt32(state, EPersistLoadStatePrepareUnloading, EPersistLoadStateMemory) {
				} else {
				}
			}
		default:
		}
	}
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 未写入成功数据, 添加到失败队列
	func (m *{{.DataName}}Manager) DataToFailQueue() {
		var persistSync *{{.DataName}}Sync

		// 一旦失败标记所有的数据都是失败, 不允许导出
		{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
			m.FailQueue = append(m.FailQueue, m.InsertQueue...)
			m.InsertQueue = m.InsertQueue[0:0]
		{{end}}

		for i := m.syncQueue.Length(); i > 0; i-- {
			persistSync = m.syncQueue.Remove().(*{{.DataName}}Sync)
			switch persistSync.Op {
			case E{{.DataName}}OpInsert, E{{.DataName}}OpUpdate, E{{.DataName}}OpDelete:
				m.FailQueue = append(m.FailQueue, persistSync)
			{{if .HashIndexUnload}}
				case E{{.DataName}}OpUnload:
					// 导出状态还原
					cls := persistSync.Data
					{{index .HashIndexUnload.Cols 0}} := cls.{{index .HashIndexUnload.Cols 0}}
					if value, ok := m.load{{index .HashIndexUnload.Cols 0}}Map.Load({{index .HashIndexUnload.Cols 0}}); ok {
						state := value
						// 导出失败状态回退
						if atomic.CompareAndSwapInt32(state, E{{.DataName}}LoadStatePrepareUnloading, E{{.DataName}}LoadStateMemory) {
						} else {
						}
					}
			{{end}}

			default:
			}
		}
	}
{{end}}


{{/* SaveFile }}
{{if $.ArgsInfo.Save}}
// 文件读取写回失败数据
func (m *PersistManager) LoadFile() error {
	bombExist := util.Exists("./G_MyProjectGo_ultraman_src_menet_persist_tests_model/Persist.bomb")
	tmpExist := util.Exists("./G_MyProjectGo_ultraman_src_menet_persist_tests_model/Persist.tmp")

	if tmpExist {
		return persistCore.EPersistErrorTempFileExist
	}

	if bombExist {
		data, err := ioutil.ReadFile("./G_MyProjectGo_ultraman_src_menet_persist_tests_model/Persist.bomb")
		if err != nil {
			return err
		}
		pos := bytes.IndexByte(data, byte(' '))
		if pos == -1 {
			return persistCore.EPersistErrorInvalidBombFile
		}
		persistData := data[pos+1:]
		err = json.Unmarshal(persistData, &m.FailQueue)
		if err != nil {
			return err
		}
	}
	return nil
}

{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 文件读取写回失败数据
	func (m *{{.DataName}}Manager) LoadFile() error {
		bombExist := util.Exists("{{.ArgsInfo.BombDir}}/{{.DataName}}.bomb")
		tmpExist := util.Exists("{{.ArgsInfo.BombDir}}/{{.DataName}}.tmp")

		if tmpExist {
			return persistCore.EPersistErrorTempFileExist
		}

		if bombExist {
			data, err := ioutil.ReadFile("{{.ArgsInfo.BombDir}}/{{.DataName}}.bomb")
			if err != nil {
				return err
			}
			pos := bytes.IndexByte(data, byte(' '))
			if pos == -1 {
				return persistCore.EPersistErrorInvalidBombFile
			}
			persistData := data[pos+1:]
			err = json.Unmarshal(persistData, &m.FailQueue)
			if err != nil {
				return err
			}
		}
		return nil
	}
{{end}}


{{/* SaveFile }}
{{if $.ArgsInfo.Save}}
// 写回失败,记录数据,写文件,等待下次写回
func (m *PersistManager) SaveFile() {

	m.DataToFailQueue()

	data, err := json.Marshal(m.FailQueue)
	if err != nil {
		log.Println("SaveFile marshal error ", err)
	}
	_ = os.Mkdir("./G_MyProjectGo_demo_src_menet_persist_tests_model", 0770)
	err = ioutil.WriteFile("./???Data???/_Persist.tmp", append([]byte("Persist "), data...), 0660)
	if err != nil {
		log.Println("SaveFile write temp file error ", err)
	}
	err = ioutil.WriteFile("./???Data???/_Persist.bomb", append([]byte("Persist "), data...), 0660)
	if err != nil {
		log.Println("SaveFile write bomb file error ", err)
	}
	_ = os.Remove("./G_MyProjectGo_demo_src_menet_persist_tests_model/Persist.tmp")
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 写回失败,记录数据,写文件,等待下次写回
	func (m *{{.DataName}}Manager) SaveFile() {

		m.DataToFailQueue()

		data, err := json.Marshal(m.FailQueue)
		if err != nil {
			log.Println("SaveFile marshal error ", err)
		}
		_ = os.Mkdir("{{.ArgsInfo.BombDir}}", 0770)
		err = ioutil.WriteFile("{{.ArgsInfo.BombDir}}/{{.DataName}}.tmp", append([]byte("{{.DataName}} "), data...), 0660)
		if err != nil {
			log.Println("SaveFile write temp file error ", err)
		}
		err = ioutil.WriteFile("{{.ArgsInfo.BombDir}}/{{.DataName}}.bomb", append([]byte("{{.DataName}} "), data...), 0660)
		if err != nil {
			log.Println("SaveFile write bomb file error ", err)
		}
		_ = os.Remove("{{.ArgsInfo.BombDir}}/{{.DataName}}.tmp")
	}
{{end}}


{{/* RemoveFile }}
{{if $.ArgsInfo.Save}}
// 删除写回失败文件
func (m *PersistManager) RemoveFile() {
	_ = os.Remove("./G_MyProjectGo_demo_src_menet_persist_tests_model/Persist.bomb")
	_ = os.Remove("./G_MyProjectGo_demo_src_menet_persist_tests_model/Persist.tmp")
	_ = os.Remove("./G_MyProjectGo_demo_src_menet_persist_tests_model/")
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 删除写回失败文件
	func (m *{{.DataName}}Manager) RemoveFile() {
		_ = os.Remove("{{.ArgsInfo.BombDir}}/{{.DataName}}.tmp")
		_ = os.Remove("{{.ArgsInfo.BombDir}}/{{.DataName}}.bomb")
		_ = os.Remove("{{.ArgsInfo.BombDir}}")
	}
{{else}}
	// 删除写回失败文件
	func (m *{{.DataName}}Manager) RemoveFile() {
	}
{{end}}

{{/* RecoverBomb }}
{{if $.ArgsInfo.Save}}
// bomb数据写入数据库
func (m *PersistManager) RecoverBomb(bomb []byte) (err error) {
	var persistSync *PersistSync
	var failQueue []*PersistSync
	session := m.engine.NewSession()
	defer session.Close()
	err = json.Unmarshal(bomb, &failQueue)
	if err != nil {
		return
	}
	var i int
	for i = range failQueue {
		persistSync = failQueue[i]
		err = m.SaveDB(session, persistSync)
		if err != nil {
			break
		}
	}
	if len(failQueue)-1 > i {
		data, _ := json.Marshal(failQueue[i:])
		_, _ = os.Stdout.Write([]byte("Persist "))
		_, _ = os.Stdout.Write(data)
	}
	return
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// bomb数据写入数据库
	func (m *{{.DataName}}Manager) RecoverBomb(bomb []byte) (err error) {
		var persistSync *{{.DataName}}Sync
		var failQueue []*{{.DataName}}Sync
		session := m.engine.NewSession()
		defer session.Close()
		err = json.Unmarshal(bomb, &failQueue)
		if err != nil {
			return
		}
		var i int
		for i = range failQueue {
			persistSync = failQueue[i]
			err = m.SaveDB(session, persistSync)
			if err != nil {
				break
			}
		}
		if len(failQueue)-1 > i {
			data, _ := json.Marshal(failQueue[i:])
			_, _ = os.Stdout.Write([]byte("{{.DataName}} "))
			_, _ = os.Stdout.Write(data)
		}
		return
	}
{{else}}
	// bomb数据写入数据库
	func (m *{{.DataName}}Manager) RecoverBomb(bomb []byte) (err error) {
		return
	}
{{end}}

{{/* merge queue }}
{{if $.ArgsInfo.Save}}
// 内存中合并操作
func (m *PersistManager) MergeQueue(q *queue.Queue) {
	var currentPersistSync *PersistSync
	var oldPersistSync *PersistSync
	var ok bool

	var unloadList []*PersistSync

	// 合并可能失败, persistSyncMap必须创建副本
	persistSyncMap := map[PersistUidId]*PersistSync{}

	//unload 按照顺序强制移到最后
	//insert update delete 按照主键合并
	lenSyncQueue := q.Length()
	fail := false

LabelForSyncQueue:
	for i := 0; i < lenSyncQueue; i++ {
		currentPersistSync = q.Get(i).(*PersistSync)
		pk := PersistUidId{
			Uid: currentPersistSync.Data.Uid,
			Id:  currentPersistSync.Data.Id,
		}
		// 导出特殊处理
		if currentPersistSync.Op == EPersistOpUnload {
			unloadList = append(unloadList, currentPersistSync)
			continue
		}
		// 第一次出现直接拷贝
		if oldPersistSync, ok = persistSyncMap[pk]; !ok {
			persistSyncMap[pk] = &PersistSync{Data: currentPersistSync.Data, Op: currentPersistSync.Op}
			continue
		}

		switch oldPersistSync.Op {
		case EPersistOpInsert:
			switch currentPersistSync.Op {
			case EPersistOpInsert:
				fail = true
				break LabelForSyncQueue
			case EPersistOpUpdate:
				oldPersistSync.Op = EPersistOpInsert
				oldPersistSync.Data = currentPersistSync.Data
			case EPersistOpDelete:
				delete(persistSyncMap, pk)
			}
		case EPersistOpUpdate:
			switch currentPersistSync.Op {
			case EPersistOpInsert:
				fail = true
				break LabelForSyncQueue
			case EPersistOpUpdate:
				oldPersistSync.Op = EPersistOpUpdate
				oldPersistSync.Data = currentPersistSync.Data
			case EPersistOpDelete:
				oldPersistSync.Op = EPersistOpDelete
				oldPersistSync.Data = currentPersistSync.Data
			}
		case EPersistOpDelete:
			switch currentPersistSync.Op {
			case EPersistOpInsert:
				oldPersistSync.Op = EPersistOpUpdate
				oldPersistSync.Data = currentPersistSync.Data
			case EPersistOpUpdate:
				fail = true
				break LabelForSyncQueue
			case EPersistOpDelete:
				fail = true
				break LabelForSyncQueue
			}
		}
	}
	// 遇到错误取消合并
	if fail {
		return
	}

	// 清空队列
	for i := q.Length(); i > 0; i-- {
		q.Remove()
	}
	{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
		// 按照合并内容重建队列, 插入特殊处理
		for _, persistSync := range persistSyncMap {
			if persistSync.Op == EPersistOpInsert {
				m.InsertQueue = append(m.InsertQueue, persistSync)
			} else {
				q.Add(persistSync)
			}
		}
	{{else}}
		// 按照合并内容重建队列
		for _, persistSync := range persistSyncMap {
			q.Add(persistSync)
		}
	{{end}}
	for _, persistSync := range unloadList {
		q.Add(persistSync)
	}
}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 内存中合并操作
	func (m *{{.DataName}}Manager) MergeQueue(q *queue.Queue) {
		{{if .HashIndexPk}}
			var currentPersistSync *{{.DataName}}Sync
			var oldPersistSync *{{.DataName}}Sync
			var ok bool

			var unloadList []*{{.DataName}}Sync

			// 合并可能失败, persistSyncMap必须创建副本
			{{if gt (.HashIndexPk.Cols|len) 1}}
				persistSyncMap := map[{{.DataName}}{{.HashIndexPk.Keys}}]*{{.DataName}}Sync{}
			{{else}}
				persistSyncMap := map[{{index .HashIndexPk.Types 0}}]*{{.DataName}}Sync{}
			{{end}}

			//unload 按照顺序强制移到最后
			//insert update delete 按照主键合并
			lenSyncQueue := q.Length()
			fail := false

		LabelForSyncQueue:
			for i := 0; i < lenSyncQueue; i++ {
				currentPersistSync = q.Get(i).(*{{.DataName}}Sync)
				{{if gt (.HashIndexPk.Cols|len) 1}}
					pk := {{.DataName}}{{.HashIndexPk.Keys}}{
						{{range $i, $col := .HashIndexPk.Cols}}
							{{$col}}: currentPersistSync.Data.{{$col}},
						{{end}}
					}
				{{else}}
					pk := currentPersistSync.Data.{{.HashIndexPk.Keys}}
				{{end}}
				// 导出特殊处理
				if currentPersistSync.Op == E{{.DataName}}OpUnload {
					unloadList = append(unloadList, currentPersistSync)
					continue
				}
				// 第一次出现直接拷贝
				if oldPersistSync, ok = persistSyncMap[pk]; !ok {
					persistSyncMap[pk] = &{{.DataName}}Sync{Data: currentPersistSync.Data, Op: currentPersistSync.Op}
					continue
				}

				switch oldPersistSync.Op {
				case E{{.DataName}}OpInsert:
					switch currentPersistSync.Op {
					case E{{.DataName}}OpInsert:
						fail = true
						break LabelForSyncQueue
					case E{{.DataName}}OpUpdate:
						oldPersistSync.Op = E{{.DataName}}OpInsert
						oldPersistSync.Data = currentPersistSync.Data
					case E{{.DataName}}OpDelete:
						delete(persistSyncMap, pk)
					}
				case E{{.DataName}}OpUpdate:
					switch currentPersistSync.Op {
					case E{{.DataName}}OpInsert:
						fail = true
						break LabelForSyncQueue
					case E{{.DataName}}OpUpdate:
						oldPersistSync.Op = E{{.DataName}}OpUpdate
						oldPersistSync.Data = currentPersistSync.Data
					case E{{.DataName}}OpDelete:
						oldPersistSync.Op = E{{.DataName}}OpDelete
						oldPersistSync.Data = currentPersistSync.Data
					}
				case E{{.DataName}}OpDelete:
					switch currentPersistSync.Op {
					case E{{.DataName}}OpInsert:
						oldPersistSync.Op = E{{.DataName}}OpUpdate
						oldPersistSync.Data = currentPersistSync.Data
					case E{{.DataName}}OpUpdate:
						fail = true
						break LabelForSyncQueue
					case E{{.DataName}}OpDelete:
						fail = true
						break LabelForSyncQueue
					}
				}
			}
			// 遇到错误取消合并
			if fail {
				return
			}

			// 清空队列
			for i := q.Length(); i > 0; i-- {
				q.Remove()
			}

			{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
				// 按照合并内容重建队列, 插入特殊处理
				for _, persistSync := range persistSyncMap {
					if persistSync.Op == E{{.DataName}}OpInsert {
						m.InsertQueue = append(m.InsertQueue, persistSync)
					} else {
						q.Add(persistSync)
					}
				}
			{{else}}
				// 按照合并内容重建队列
				for _, persistSync := range persistSyncMap {
					q.Add(persistSync)
				}
			{{end}}

			for _, persistSync := range unloadList {
				q.Add(persistSync)
			}
		{{else}}

		{{end}}
	}
{{end}}


{{/* async save }}
{{if $.ArgsInfo.Save}}
// 异步写回
func (m *PersistManager) AsyncSave() {
	bTime := time.Now().UnixNano()
	defer func() {
		if r := recover(); r != nil {
			log.Println("recovered in ", r)
			log.Println("stack: ", debug.Stack())
		}
		m.DataToFailQueue()
		m.lastWriteBackTime = time.Duration(time.Now().UnixNano() - bTime)
		m.syncEnd <- true
	}()
	
	var persistSync *PersistSync
	var err error
	needCollect := <-m.syncBegin
	if needCollect && m.syncQueue.Length() == 0 {
		time.Sleep(time.Millisecond * 100)
		return
	}
	session := m.engine.NewSession()
	defer session.Close()

	m.MergeQueue(m.syncQueue)

	for i := range m.FailQueue {
		persistSync = m.FailQueue[i]
		err = m.SaveDB(session, persistSync)
		if err != nil {
			m.FailQueue = m.FailQueue[i:]
			m.SaveFile()
			return
		}
	}
	m.FailQueue = m.FailQueue[0:0]

{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
	multiInsertFn := func() bool {
		var err error
		defer func() {
			if err == nil {
				m.InsertQueue = m.InsertQueue[0:0]
			} else {
				_ = session.Rollback()
			}
		}()

		if len(m.InsertQueue) <= 0 {
			return true
		}
		err = session.Begin()
		if err != nil {
			return false
		}

		const num = 100
		var insertArray [num]*Persist
		length := len(m.InsertQueue)
		quotient := length / num
		remainder := length % num
		for i := 0; i < quotient; i++ {
			//fmt.Println("s1->(", i*num, "-", (i+1)*num, "): ", m.InsertQueue[i*num:(i+1)*num])
			for j := 0; j < num; j++ {
				insertArray[j] = m.InsertQueue[i*num+j].Data
			}
			_, err = session.InsertMulti(insertArray[:])
			if err != nil {
				log.Println("InsertMulti error ", err)
				return false
			}
		}
		if remainder != 0 {
			//fmt.Println("s1->(", quotient*num, "-", length, "): ", m.InsertQueue[quotient*num:length])
			for j := 0; j < remainder; j++ {
				insertArray[j] = m.InsertQueue[quotient*num+j].Data
			}
			_, err = session.InsertMulti(insertArray[:remainder])
			if err != nil {
				log.Println("InsertMulti error ", err)
				return false
			}
		}
		err = session.Commit()
		if err != nil {
			return false
		}
		return true
	}

	multiInsertSuccess := multiInsertFn()

	// 批量插入失败, 改为单条插入
	if !multiInsertSuccess {
		for idx, persistSync := range m.InsertQueue {
			err = m.SaveDB(session, persistSync)
			if err != nil {
				m.InsertQueue = m.InsertQueue[idx:]
				m.SaveFile()
				break
			}
		}
		m.InsertQueue = m.InsertQueue[0:0]
	}
{{end}}

	for i := m.syncQueue.Length(); i > 0; i-- {
		persistSync = m.syncQueue.Peek().(*PersistSync)
		err = m.SaveDB(session, persistSync)
		if err == nil {
			persistSync = m.syncQueue.Remove().(*PersistSync)
		} else {
			m.SaveFile()
			return
		}
	}
	m.RemoveFile()
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 异步写回
	func (m *{{.DataName}}Manager) AsyncSave() {
		bTime := time.Now().UnixNano()
		defer func() {
			if r := recover(); r != nil {
				log.Println("recovered in ", r)
				log.Println("stack: ", debug.Stack())
			}
			m.DataToFailQueue()
			m.lastWriteBackTime = time.Duration(time.Now().UnixNano() - bTime)
			m.syncEnd <- true
		}()
		
		var persistSync *{{.DataName}}Sync
		var err error
		needCollect := <-m.syncBegin
		if needCollect && m.syncQueue.Length() == 0 {
			time.Sleep(time.Millisecond * 100)
			return
		}
		session := m.engine.NewSession()
		defer session.Close()

		{{if .ArgsInfo.OptimizeFlagSQLMerge}}
			m.MergeQueue(m.syncQueue)
		{{end}}

		for i := range m.FailQueue {
			persistSync = m.FailQueue[i]
			err = m.SaveDB(session, persistSync)
			if err != nil {
				m.FailQueue = m.FailQueue[i:]
				m.SaveFile()
				return
			}
		}
		m.FailQueue = m.FailQueue[0:0]

		{{if .ArgsInfo.OptimizeFlagSQLInsertMerge}}
			multiInsertFn := func() bool {
				var err error
				defer func() {
					if err == nil {
						m.InsertQueue = m.InsertQueue[0:0]
					} else {
						_ = session.Rollback()
					}
				}()

				if len(m.InsertQueue) <= 0 {
					return true
				}
				err = session.Begin()
				if err != nil {
					return false
				}

				const num = {{.ArgsInfo.MaxInsertRows}}
				var insertArray [num]*{{.DataName}}
				length := len(m.InsertQueue)
				quotient := length / num
				remainder := length % num
				for i := 0; i < quotient; i++ {
					//fmt.Println("queue->(", i*num, "-", (i+1)*num, "): ", m.InsertQueue[i*num:(i+1)*num])
					for j := 0; j < num; j++ {
						insertArray[j] = m.InsertQueue[i*num+j].Data
					}
					_, err = session.InsertMulti(insertArray[:])
					if err != nil {
						log.Println("InsertMulti error ", err)
						return false
					}
				}
				if remainder != 0 {
					//fmt.Println("queue->(", quotient*num, "-", length, "): ", m.InsertQueue[quotient*num:length])
					for j := 0; j < remainder; j++ {
						insertArray[j] = m.InsertQueue[quotient*num+j].Data
					}
					_, err = session.InsertMulti(insertArray[:remainder])
					if err != nil {
						log.Println("InsertMulti error ", err)
						return false
					}
				}
				err = session.Commit()
				if err != nil {
					return false
				}
				return true
			}

			multiInsertSuccess := multiInsertFn()

			// 批量插入失败, 改为单条插入
			if !multiInsertSuccess {
				for idx, persistSync := range m.InsertQueue {
					err = m.SaveDB(session, persistSync)
					if err != nil {
						m.InsertQueue = m.InsertQueue[idx:]
						m.SaveFile()
						break
					}
				}
				m.InsertQueue = m.InsertQueue[0:0]
			}
		{{end}}


		for i := m.syncQueue.Length(); i > 0; i-- {
			persistSync = m.syncQueue.Peek().(*{{.DataName}}Sync)
			err = m.SaveDB(session, persistSync)
			if err == nil {
				persistSync = m.syncQueue.Remove().(*{{.DataName}}Sync)
			} else {
				m.SaveFile()
				return
			}
		}
		m.RemoveFile()
	}
{{end}}







{{/* collect }}
{{if $.ArgsInfo.Save}}
	// 收集数据
	func (m *PersistManager) Collect() {
		var persistSync *PersistSync
		var ok bool
		// 0:normal  1:exit begin, save sync  2:save cache  3:save done
		var state int8
		go m.AsyncSave()
		m.syncBegin <- true
		for {
			select {
			case persistSync, ok = <-m.syncChan:
				if ok {
					m.cacheQueue.Add(persistSync)
				}
			case _, ok = <-m.syncEnd:
				if ok {
					m.CheckOverload()
					m.cacheQueue, m.syncQueue = m.syncQueue, m.cacheQueue
					switch state {
					case EPersistCollectStateNormal:
						go m.AsyncSave()
						m.syncBegin <- true
					case EPersistCollectStateSaveSync:
						go m.AsyncSave()
						m.syncBegin <- false
						state = EPersistCollectStateSaveCache
					case EPersistCollectStateSaveCache:
						go m.AsyncSave()
						m.syncBegin <- false
						state = EPersistCollectStateSaveDone
					case EPersistCollectStateSaveDone:
						m.exitEnd <- true
						return
					}
				}
			case _, ok = <-m.exitBegin:
				if ok {
					state = EPersistCollectStateSaveSync
				}
			//default:
			//	time.Sleep(time.Second/10)
			}
		}
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 收集数据
	func (m *{{.DataName}}Manager) Collect() {
		var persistSync *{{.DataName}}Sync
		var ok bool
		// 0:normal  1:exit begin, save sync  2:save cache  3:save done
		var state int8
		go m.AsyncSave()
		m.syncBegin <- true
		for {
			select {
			case persistSync, ok = <-m.syncChan:
				if ok {
					m.cacheQueue.Add(persistSync)
				}
			case _, ok = <-m.syncEnd:
				if ok {
					m.CheckOverload()
					m.cacheQueue, m.syncQueue = m.syncQueue, m.cacheQueue
					switch state {
					case E{{.DataName}}CollectStateNormal:
						go m.AsyncSave()
						m.syncBegin <- true
					case E{{.DataName}}CollectStateSaveSync:
						go m.AsyncSave()
						m.syncBegin <- false
						state = E{{.DataName}}CollectStateSaveCache
					case E{{.DataName}}CollectStateSaveCache:
						go m.AsyncSave()
						m.syncBegin <- false
						state = E{{.DataName}}CollectStateSaveDone
					case E{{.DataName}}CollectStateSaveDone:
						m.exitEnd <- true
						return
					}
				}
			case _, ok = <-m.exitBegin:
				if ok {
					state = E{{.DataName}}CollectStateSaveSync
				}
			//default:
			//	time.Sleep(time.Second/10)
			}
		}
	}
{{end}}


{{/* exit }}
{{if $.ArgsInfo.Save}}
	// 管理类退出
	func (m *PersistManager) Exit(wg *sync.WaitGroup) {
		defer wg.Done()

		if atomic.LoadInt32(&m.managerState) != EPersistManagerStateNormal {
			return
		}

		m.exitBegin <- true
		<-m.exitEnd
		atomic.StoreInt32(&m.managerState, EPersistManagerStateIdle)
		return
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 管理类退出
	func (m *{{.DataName}}Manager) Exit(wg *sync.WaitGroup) {
		defer wg.Done()

		if atomic.LoadInt32(&m.managerState) != E{{.DataName}}ManagerStateNormal {
			return
		}

		m.exitBegin <- true
		<-m.exitEnd
		atomic.StoreInt32(&m.managerState, E{{.DataName}}ManagerStateIdle)
		return
	}
{{end}}


{{/* sync }}
{{if $.ArgsInfo.Save}}
	// 数据库表结构同步
	func (m *PersistManager) Sync() (err error) {
		err = m.engine.Sync(gPersistNil)
		return
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 数据库表结构同步
	func (m *{{.DataName}}Manager) Sync() (err error) {
		err = m.engine.Sync(g{{.DataName}}Nil)
		return
	}
{{end}}


{{/* exit }}
{{if $.ArgsInfo.Save}}
	// 全部内存数据写入数据库, 本接口耗时长,仅用于停服后.  补救没有标记写回数据(只处理未标记数据,New Delete不存在漏写)
	func (m *PersistManager) SyncData(wg *sync.WaitGroup) (err error) {
		defer wg.Done()
		update := func(session *xorm.Session, cls *Persist, memData, dbData []byte) {
			log.Println("SyncData error. missing mark.", string(memData))
			log.Println("SyncData error. missing mark.", string(dbData))
			_, err = session.ID(core.NewPK(cls.Uid, cls.Id, )).AllCols().Update(cls)
			if err != nil {
				log.Println("SyncData update error.", err, "[sql error]", cls)
				return
			}
		}
		resetTimeNSec := func(clsMem, clsDb *Role) {
			defer func() {
				if r := recover(); r != nil {
				}
			}()
			typeF := reflect.TypeOf(*clsMem)
			valueMemF := reflect.ValueOf(clsMem).Elem()
			valueDbF := reflect.ValueOf(clsDb).Elem()
			for i := 0; i < typeF.NumField(); i++ {
				if typeF.Field(i).Type.Name() == "Time" {
					f := valueMemF.Field(i)
					if f.CanInterface() {
						v := time.Unix(f.Interface().(time.Time).Unix(), 0)
						f.Set(reflect.ValueOf(v))
					}
					vMem := valueMemF.Field(i).Interface().(time.Time)
					vDb := valueDbF.Field(i).Interface().(time.Time)
					if vMem.Equal(vDb) {
						f.Set(reflect.ValueOf(vDb))
					}
				}
			}
		}
		session := m.engine.NewSession()
		defer session.Close()
		for _, cls := range m.GetAll() {
			dbCls := &Persist{Uid: cls.Uid, Id: cls.Id}
			var has bool
			has, err = session.Get(dbCls)
			if err != nil || !has {
				log.Println("SyncData query error.", err, "[data error]", cls)
				continue
			}
			memCls := m.GetPersistByUidId(cls.Uid, cls.Id)
			if memCls != nil {
				resetTimeNSec(memCls, dbCls)
				// 后期生成比较代码
				memData, _ := json.Marshal(memCls)
				dbData, _ := json.Marshal(dbCls)
				// 数据库内存不一致
				if !bytes.Equal(memData, dbData) {
					update(session, memCls, memData, dbData)
				}
			}
		}
		return
	}
{{end}}
{{*/}}
{{if $.ArgsInfo.Save}}
	// 全部内存数据写入数据库, 本接口耗时长,仅用于停服后.  补救没有标记写回数据(只处理未标记数据,New Delete不存在漏写)
	func (m *{{.DataName}}Manager) SyncData(wg *sync.WaitGroup) (err error) {
		defer wg.Done()
		{{if .HashIndexPk}}
			update := func(session *xorm.Session, cls *{{.DataName}}, memData, dbData []byte) {
				log.Println("SyncData error. missing mark.", string(memData))
				log.Println("SyncData error. missing mark.", string(dbData))
				_, err = session.ID(core.NewPK({{.HashIndexPk.ClsPointKeys}})).AllCols().Update(cls)
				if err != nil {
					log.Println("SyncData update error.", err, "[sql error]", cls)
					return
				}
			}
			resetTimeNSec := func(clsMem, clsDb *{{.DataName}}) {
				defer func() {
					if r := recover(); r != nil {
					}
				}()
				typeF := reflect.TypeOf(*clsMem)
				valueMemF := reflect.ValueOf(clsMem).Elem()
				valueDbF := reflect.ValueOf(clsDb).Elem()
				for i := 0; i < typeF.NumField(); i++ {
					if typeF.Field(i).Type.Name() == "Time" {
						f := valueMemF.Field(i)
						if f.CanInterface() {
							v := time.Unix(f.Interface().(time.Time).Unix(), 0)
							f.Set(reflect.ValueOf(v))
						}
						vMem := valueMemF.Field(i).Interface().(time.Time)
						vDb := valueDbF.Field(i).Interface().(time.Time)
						if vMem.Equal(vDb) {
							f.Set(reflect.ValueOf(vDb))
						}
					}
				}
			}
			session := m.engine.NewSession()
			defer session.Close()
			for _, cls := range m.GetAll() {
				dbCls := &{{.DataName}}{
						{{range $i, $col := .HashIndexPk.Cols}}
							{{$col}}: cls.{{$col}},
						{{end}}
				}
				var has bool
				has, err = session.Get(dbCls)
				if err != nil || !has {
					log.Println("SyncData query error.", err, "[data error]", cls)
					continue
				}
				memCls := m.Get{{.DataName}}By{{.HashIndexPk.Keys}}({{.HashIndexPk.ClsPointKeys}})
				if memCls != nil {
					resetTimeNSec(memCls, dbCls)
					// 后期生成比较代码
					memData, _ := json.Marshal(memCls)
					dbData, _ := json.Marshal(dbCls)
					// 数据库内存不一致
					if !bytes.Equal(memData, dbData) {
						update(session, memCls, memData, dbData)
					}
				}
			}
			return
		{{else}}
			return
		{{end}}
	}
{{end}}



`
